/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Address } from "@/entities/Address";

import type {
  Agent,
  Agents,
  CreateAgentReq,
  CreateAgentResp,
  DeployAgentReq,
  DeployAgentResp,
  SaveAgentResp,
  SignedContract,
} from "../models/index";

import {
  AgentFromJSON,
  AgentsFromJSON,
  CreateAgentReqToJSON,
  CreateAgentRespFromJSON,
  DeployAgentReqToJSON,
  DeployAgentRespFromJSON,
  SaveAgentRespFromJSON,
  SignedContractToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface ApiAiAgentsAddressGetRequest {
  address: Address;
}

export interface ApiAiAgentsAddressIdVersionsGetRequest {
  address: Address;
  id: string;
}

export interface ApiAiAgentsAddressIdVersionsVersionGetRequest {
  address: Address;
  id: string;
  version: string;
}

export interface ApiAiAgentsCreatePreparePostRequest {
  createAgentReq: CreateAgentReq;
}

export interface ApiAiAgentsCreateSendPostRequest {
  signedContract: SignedContract;
}

export interface ApiAiAgentsDeployPreparePostRequest {
  deployAgentReq: DeployAgentReq;
}

export interface ApiAiAgentsDeploySendPostRequest {
  signedContract: SignedContract;
}

export interface ApiAiAgentsIdSavePreparePostRequest {
  createAgentReq: CreateAgentReq;
  id: string;
}

export interface ApiAiAgentsIdSaveSendPostRequest {
  id: string;
  signedContract: SignedContract;
}

/**
 *
 */
export class AIAgentsApi extends runtime.BaseAPI {
  /**
   */
  async apiAiAgentsAddressGetRaw(
    requestParameters: ApiAiAgentsAddressGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Agents>> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiAiAgentsAddressGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/ai-agents/{address}`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address.value)),
    );

    const response = await this.request(
      {
        headers: headerParameters,
        method: "GET",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AgentsFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsAddressGet(
    requestParameters: ApiAiAgentsAddressGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Agents> {
    const response = await this.apiAiAgentsAddressGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsAddressIdVersionsGetRaw(
    requestParameters: ApiAiAgentsAddressIdVersionsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Agents>> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiAiAgentsAddressIdVersionsGet().',
      );
    }

    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiAiAgentsAddressIdVersionsGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/ai-agents/{address}/{id}/versions`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address.value)),
    );
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        headers: headerParameters,
        method: "GET",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AgentsFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsAddressIdVersionsGet(
    requestParameters: ApiAiAgentsAddressIdVersionsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Agents> {
    const response = await this.apiAiAgentsAddressIdVersionsGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsAddressIdVersionsVersionGetRaw(
    requestParameters: ApiAiAgentsAddressIdVersionsVersionGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Agent>> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiAiAgentsAddressIdVersionsVersionGet().',
      );
    }

    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiAiAgentsAddressIdVersionsVersionGet().',
      );
    }

    if (requestParameters.version == null) {
      throw new runtime.RequiredError(
        "version",
        'Required parameter "version" was null or undefined when calling apiAiAgentsAddressIdVersionsVersionGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/ai-agents/{address}/{id}/versions/{version}`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address.value)),
    );
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );
    urlPath = urlPath.replace(
      `{version}`,
      encodeURIComponent(String(requestParameters.version)),
    );

    const response = await this.request(
      {
        headers: headerParameters,
        method: "GET",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AgentFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsAddressIdVersionsVersionGet(
    requestParameters: ApiAiAgentsAddressIdVersionsVersionGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Agent> {
    const response = await this.apiAiAgentsAddressIdVersionsVersionGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsCreatePreparePostRaw(
    requestParameters: ApiAiAgentsCreatePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<CreateAgentResp>> {
    if (requestParameters.createAgentReq == null) {
      throw new runtime.RequiredError(
        "createAgentReq",
        'Required parameter "createAgentReq" was null or undefined when calling apiAiAgentsCreatePreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/ai-agents/create/prepare`;

    const response = await this.request(
      {
        body: CreateAgentReqToJSON(requestParameters.createAgentReq),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      CreateAgentRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsCreatePreparePost(
    requestParameters: ApiAiAgentsCreatePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<CreateAgentResp> {
    const response = await this.apiAiAgentsCreatePreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsCreateSendPostRaw(
    requestParameters: ApiAiAgentsCreateSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.signedContract == null) {
      throw new runtime.RequiredError(
        "signedContract",
        'Required parameter "signedContract" was null or undefined when calling apiAiAgentsCreateSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/ai-agents/create/send`;

    const response = await this.request(
      {
        body: SignedContractToJSON(requestParameters.signedContract),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async apiAiAgentsCreateSendPost(
    requestParameters: ApiAiAgentsCreateSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.apiAiAgentsCreateSendPostRaw(requestParameters, initOverrides);
  }

  /**
   */
  async apiAiAgentsDeployPreparePostRaw(
    requestParameters: ApiAiAgentsDeployPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DeployAgentResp>> {
    if (requestParameters.deployAgentReq == null) {
      throw new runtime.RequiredError(
        "deployAgentReq",
        'Required parameter "deployAgentReq" was null or undefined when calling apiAiAgentsDeployPreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/ai-agents/deploy/prepare`;

    const response = await this.request(
      {
        body: DeployAgentReqToJSON(requestParameters.deployAgentReq),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DeployAgentRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsDeployPreparePost(
    requestParameters: ApiAiAgentsDeployPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DeployAgentResp> {
    const response = await this.apiAiAgentsDeployPreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsDeploySendPostRaw(
    requestParameters: ApiAiAgentsDeploySendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.signedContract == null) {
      throw new runtime.RequiredError(
        "signedContract",
        'Required parameter "signedContract" was null or undefined when calling apiAiAgentsDeploySendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/ai-agents/deploy/send`;

    const response = await this.request(
      {
        body: SignedContractToJSON(requestParameters.signedContract),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async apiAiAgentsDeploySendPost(
    requestParameters: ApiAiAgentsDeploySendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.apiAiAgentsDeploySendPostRaw(requestParameters, initOverrides);
  }

  /**
   */
  async apiAiAgentsIdSavePreparePostRaw(
    requestParameters: ApiAiAgentsIdSavePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SaveAgentResp>> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiAiAgentsIdSavePreparePost().',
      );
    }

    if (requestParameters.createAgentReq == null) {
      throw new runtime.RequiredError(
        "createAgentReq",
        'Required parameter "createAgentReq" was null or undefined when calling apiAiAgentsIdSavePreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/ai-agents/{id}/save/prepare`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        body: CreateAgentReqToJSON(requestParameters.createAgentReq),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SaveAgentRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsIdSavePreparePost(
    requestParameters: ApiAiAgentsIdSavePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SaveAgentResp> {
    const response = await this.apiAiAgentsIdSavePreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsIdSaveSendPostRaw(
    requestParameters: ApiAiAgentsIdSaveSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiAiAgentsIdSaveSendPost().',
      );
    }

    if (requestParameters.signedContract == null) {
      throw new runtime.RequiredError(
        "signedContract",
        'Required parameter "signedContract" was null or undefined when calling apiAiAgentsIdSaveSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/ai-agents/{id}/save/send`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        body: SignedContractToJSON(requestParameters.signedContract),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async apiAiAgentsIdSaveSendPost(
    requestParameters: ApiAiAgentsIdSaveSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.apiAiAgentsIdSaveSendPostRaw(requestParameters, initOverrides);
  }
}
