/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  Address,
  AgentsTeam,
  AgentsTeams,
  CreateAgentsTeamReq,
  DeleteAgentsTeamResp,
  DeployAgentsTeamReq,
  PrepareResponseCreateAgentsTeamResp,
  PrepareResponseDeployAgentsTeamResp,
  PrepareResponsePublishToFireskyResp,
  PrepareResponseRunResp,
  PrepareResponseSaveAgentsTeamResp,
  PublishToFireskyReq,
  RunReq,
  SendRequestBodyDeploySignedAgentsTeamReqDeployAgentsTeamReqDeployAgentsTeamResp,
  SendRequestBodyDeploySignedRunOnFireskyReqRunReqRunResp,
  SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp,
  SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp,
  SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp,
  SendRequestBodySignedContractRunReqRunResp,
  SendResp,
  SignedContract,
} from "../models/index";

import {
  AgentsTeamFromJSON,
  AgentsTeamsFromJSON,
  CreateAgentsTeamReqToJSON,
  DeleteAgentsTeamRespFromJSON,
  DeployAgentsTeamReqToJSON,
  PrepareResponseCreateAgentsTeamRespFromJSON,
  PrepareResponseDeployAgentsTeamRespFromJSON,
  PrepareResponsePublishToFireskyRespFromJSON,
  PrepareResponseRunRespFromJSON,
  PrepareResponseSaveAgentsTeamRespFromJSON,
  PublishToFireskyReqToJSON,
  RunReqToJSON,
  SendRequestBodyDeploySignedAgentsTeamReqDeployAgentsTeamReqDeployAgentsTeamRespToJSON,
  SendRequestBodyDeploySignedRunOnFireskyReqRunReqRunRespToJSON,
  SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamRespToJSON,
  SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamRespToJSON,
  SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyRespToJSON,
  SendRequestBodySignedContractRunReqRunRespToJSON,
  SendRespFromJSON,
  SignedContractToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface ApiAiAgentsTeamsAddressGetRequest {
  address: Address;
}

export interface ApiAiAgentsTeamsAddressIdPublishToFireskyPreparePostRequest {
  address: Address;
  id: string;
  publishToFireskyReq: PublishToFireskyReq;
}

export interface ApiAiAgentsTeamsAddressIdPublishToFireskySendPostRequest {
  address: Address;
  id: string;
  sendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp: SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp;
}

export interface ApiAiAgentsTeamsAddressIdVersionsGetRequest {
  address: Address;
  id: string;
}

export interface ApiAiAgentsTeamsAddressIdVersionsVersionGetRequest {
  address: Address;
  id: string;
  version: string;
}

export interface ApiAiAgentsTeamsCreatePreparePostRequest {
  createAgentsTeamReq: CreateAgentsTeamReq;
}

export interface ApiAiAgentsTeamsCreateSendPostRequest {
  sendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp: SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp;
}

export interface ApiAiAgentsTeamsDeployPreparePostRequest {
  deployAgentsTeamReq: DeployAgentsTeamReq;
}

export interface ApiAiAgentsTeamsDeploySendPostRequest {
  sendRequestBodyDeploySignedAgentsTeamReqDeployAgentsTeamReqDeployAgentsTeamResp: SendRequestBodyDeploySignedAgentsTeamReqDeployAgentsTeamReqDeployAgentsTeamResp;
}

export interface ApiAiAgentsTeamsIdDeletePreparePostRequest {
  id: string;
}

export interface ApiAiAgentsTeamsIdDeleteSendPostRequest {
  id: string;
  signedContract: SignedContract;
}

export interface ApiAiAgentsTeamsIdSavePreparePostRequest {
  createAgentsTeamReq: CreateAgentsTeamReq;
  id: string;
}

export interface ApiAiAgentsTeamsIdSaveSendPostRequest {
  id: string;
  sendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp: SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp;
}

export interface ApiAiAgentsTeamsRunOnFireskyPreparePostRequest {
  runReq: RunReq;
}

export interface ApiAiAgentsTeamsRunOnFireskySendPostRequest {
  sendRequestBodyDeploySignedRunOnFireskyReqRunReqRunResp: SendRequestBodyDeploySignedRunOnFireskyReqRunReqRunResp;
}

export interface ApiAiAgentsTeamsRunPreparePostRequest {
  runReq: RunReq;
}

export interface ApiAiAgentsTeamsRunSendPostRequest {
  sendRequestBodySignedContractRunReqRunResp: SendRequestBodySignedContractRunReqRunResp;
}

/**
 *
 */
export class AIAgentsTeamsApi extends runtime.BaseAPI {
  /**
   */
  async apiAiAgentsTeamsAddressGetRaw(
    requestParameters: ApiAiAgentsTeamsAddressGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AgentsTeams>> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiAiAgentsTeamsAddressGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/ai-agents-teams/{address}`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );

    const response = await this.request(
      {
        headers: headerParameters,
        method: "GET",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AgentsTeamsFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsAddressGet(
    requestParameters: ApiAiAgentsTeamsAddressGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AgentsTeams> {
    const response = await this.apiAiAgentsTeamsAddressGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsAddressIdPublishToFireskyPreparePostRaw(
    requestParameters: ApiAiAgentsTeamsAddressIdPublishToFireskyPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrepareResponsePublishToFireskyResp>> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiAiAgentsTeamsAddressIdPublishToFireskyPreparePost().',
      );
    }

    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiAiAgentsTeamsAddressIdPublishToFireskyPreparePost().',
      );
    }

    if (requestParameters.publishToFireskyReq == null) {
      throw new runtime.RequiredError(
        "publishToFireskyReq",
        'Required parameter "publishToFireskyReq" was null or undefined when calling apiAiAgentsTeamsAddressIdPublishToFireskyPreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/ai-agents-teams/{address}/{id}/publish-to-firesky/prepare`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        body: PublishToFireskyReqToJSON(requestParameters.publishToFireskyReq),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrepareResponsePublishToFireskyRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsAddressIdPublishToFireskyPreparePost(
    requestParameters: ApiAiAgentsTeamsAddressIdPublishToFireskyPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrepareResponsePublishToFireskyResp> {
    const response =
      await this.apiAiAgentsTeamsAddressIdPublishToFireskyPreparePostRaw(
        requestParameters,
        initOverrides,
      );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsAddressIdPublishToFireskySendPostRaw(
    requestParameters: ApiAiAgentsTeamsAddressIdPublishToFireskySendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiAiAgentsTeamsAddressIdPublishToFireskySendPost().',
      );
    }

    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiAiAgentsTeamsAddressIdPublishToFireskySendPost().',
      );
    }

    if (
      requestParameters.sendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp ==
      null
    ) {
      throw new runtime.RequiredError(
        "sendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp",
        'Required parameter "sendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp" was null or undefined when calling apiAiAgentsTeamsAddressIdPublishToFireskySendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/ai-agents-teams/{address}/{id}/publish-to-firesky/send`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        body: SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyRespToJSON(
          requestParameters.sendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp,
        ),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsAddressIdPublishToFireskySendPost(
    requestParameters: ApiAiAgentsTeamsAddressIdPublishToFireskySendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response =
      await this.apiAiAgentsTeamsAddressIdPublishToFireskySendPostRaw(
        requestParameters,
        initOverrides,
      );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsAddressIdVersionsGetRaw(
    requestParameters: ApiAiAgentsTeamsAddressIdVersionsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AgentsTeams>> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiAiAgentsTeamsAddressIdVersionsGet().',
      );
    }

    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiAiAgentsTeamsAddressIdVersionsGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/ai-agents-teams/{address}/{id}/versions`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        headers: headerParameters,
        method: "GET",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AgentsTeamsFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsAddressIdVersionsGet(
    requestParameters: ApiAiAgentsTeamsAddressIdVersionsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AgentsTeams> {
    const response = await this.apiAiAgentsTeamsAddressIdVersionsGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsAddressIdVersionsVersionGetRaw(
    requestParameters: ApiAiAgentsTeamsAddressIdVersionsVersionGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<AgentsTeam>> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiAiAgentsTeamsAddressIdVersionsVersionGet().',
      );
    }

    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiAiAgentsTeamsAddressIdVersionsVersionGet().',
      );
    }

    if (requestParameters.version == null) {
      throw new runtime.RequiredError(
        "version",
        'Required parameter "version" was null or undefined when calling apiAiAgentsTeamsAddressIdVersionsVersionGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/ai-agents-teams/{address}/{id}/versions/{version}`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );
    urlPath = urlPath.replace(
      `{version}`,
      encodeURIComponent(String(requestParameters.version)),
    );

    const response = await this.request(
      {
        headers: headerParameters,
        method: "GET",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      AgentsTeamFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsAddressIdVersionsVersionGet(
    requestParameters: ApiAiAgentsTeamsAddressIdVersionsVersionGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<AgentsTeam> {
    const response = await this.apiAiAgentsTeamsAddressIdVersionsVersionGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsCreatePreparePostRaw(
    requestParameters: ApiAiAgentsTeamsCreatePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrepareResponseCreateAgentsTeamResp>> {
    if (requestParameters.createAgentsTeamReq == null) {
      throw new runtime.RequiredError(
        "createAgentsTeamReq",
        'Required parameter "createAgentsTeamReq" was null or undefined when calling apiAiAgentsTeamsCreatePreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/ai-agents-teams/create/prepare`;

    const response = await this.request(
      {
        body: CreateAgentsTeamReqToJSON(requestParameters.createAgentsTeamReq),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrepareResponseCreateAgentsTeamRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsCreatePreparePost(
    requestParameters: ApiAiAgentsTeamsCreatePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrepareResponseCreateAgentsTeamResp> {
    const response = await this.apiAiAgentsTeamsCreatePreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsCreateSendPostRaw(
    requestParameters: ApiAiAgentsTeamsCreateSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    if (
      requestParameters.sendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp ==
      null
    ) {
      throw new runtime.RequiredError(
        "sendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp",
        'Required parameter "sendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp" was null or undefined when calling apiAiAgentsTeamsCreateSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/ai-agents-teams/create/send`;

    const response = await this.request(
      {
        body: SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamRespToJSON(
          requestParameters.sendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp,
        ),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsCreateSendPost(
    requestParameters: ApiAiAgentsTeamsCreateSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response = await this.apiAiAgentsTeamsCreateSendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsDeployPreparePostRaw(
    requestParameters: ApiAiAgentsTeamsDeployPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrepareResponseDeployAgentsTeamResp>> {
    if (requestParameters.deployAgentsTeamReq == null) {
      throw new runtime.RequiredError(
        "deployAgentsTeamReq",
        'Required parameter "deployAgentsTeamReq" was null or undefined when calling apiAiAgentsTeamsDeployPreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/ai-agents-teams/deploy/prepare`;

    const response = await this.request(
      {
        body: DeployAgentsTeamReqToJSON(requestParameters.deployAgentsTeamReq),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrepareResponseDeployAgentsTeamRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsDeployPreparePost(
    requestParameters: ApiAiAgentsTeamsDeployPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrepareResponseDeployAgentsTeamResp> {
    const response = await this.apiAiAgentsTeamsDeployPreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsDeploySendPostRaw(
    requestParameters: ApiAiAgentsTeamsDeploySendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    if (
      requestParameters.sendRequestBodyDeploySignedAgentsTeamReqDeployAgentsTeamReqDeployAgentsTeamResp ==
      null
    ) {
      throw new runtime.RequiredError(
        "sendRequestBodyDeploySignedAgentsTeamReqDeployAgentsTeamReqDeployAgentsTeamResp",
        'Required parameter "sendRequestBodyDeploySignedAgentsTeamReqDeployAgentsTeamReqDeployAgentsTeamResp" was null or undefined when calling apiAiAgentsTeamsDeploySendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/ai-agents-teams/deploy/send`;

    const response = await this.request(
      {
        body: SendRequestBodyDeploySignedAgentsTeamReqDeployAgentsTeamReqDeployAgentsTeamRespToJSON(
          requestParameters.sendRequestBodyDeploySignedAgentsTeamReqDeployAgentsTeamReqDeployAgentsTeamResp,
        ),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsDeploySendPost(
    requestParameters: ApiAiAgentsTeamsDeploySendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response = await this.apiAiAgentsTeamsDeploySendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsIdDeletePreparePostRaw(
    requestParameters: ApiAiAgentsTeamsIdDeletePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DeleteAgentsTeamResp>> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiAiAgentsTeamsIdDeletePreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/ai-agents-teams/{id}/delete/prepare`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DeleteAgentsTeamRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsIdDeletePreparePost(
    requestParameters: ApiAiAgentsTeamsIdDeletePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DeleteAgentsTeamResp> {
    const response = await this.apiAiAgentsTeamsIdDeletePreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsIdDeleteSendPostRaw(
    requestParameters: ApiAiAgentsTeamsIdDeleteSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiAiAgentsTeamsIdDeleteSendPost().',
      );
    }

    if (requestParameters.signedContract == null) {
      throw new runtime.RequiredError(
        "signedContract",
        'Required parameter "signedContract" was null or undefined when calling apiAiAgentsTeamsIdDeleteSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/ai-agents-teams/{id}/delete/send`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        body: SignedContractToJSON(requestParameters.signedContract),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsIdDeleteSendPost(
    requestParameters: ApiAiAgentsTeamsIdDeleteSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response = await this.apiAiAgentsTeamsIdDeleteSendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsIdSavePreparePostRaw(
    requestParameters: ApiAiAgentsTeamsIdSavePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrepareResponseSaveAgentsTeamResp>> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiAiAgentsTeamsIdSavePreparePost().',
      );
    }

    if (requestParameters.createAgentsTeamReq == null) {
      throw new runtime.RequiredError(
        "createAgentsTeamReq",
        'Required parameter "createAgentsTeamReq" was null or undefined when calling apiAiAgentsTeamsIdSavePreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/ai-agents-teams/{id}/save/prepare`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        body: CreateAgentsTeamReqToJSON(requestParameters.createAgentsTeamReq),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrepareResponseSaveAgentsTeamRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsIdSavePreparePost(
    requestParameters: ApiAiAgentsTeamsIdSavePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrepareResponseSaveAgentsTeamResp> {
    const response = await this.apiAiAgentsTeamsIdSavePreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsIdSaveSendPostRaw(
    requestParameters: ApiAiAgentsTeamsIdSaveSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiAiAgentsTeamsIdSaveSendPost().',
      );
    }

    if (
      requestParameters.sendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp ==
      null
    ) {
      throw new runtime.RequiredError(
        "sendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp",
        'Required parameter "sendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp" was null or undefined when calling apiAiAgentsTeamsIdSaveSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/ai-agents-teams/{id}/save/send`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        body: SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamRespToJSON(
          requestParameters.sendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp,
        ),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsIdSaveSendPost(
    requestParameters: ApiAiAgentsTeamsIdSaveSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response = await this.apiAiAgentsTeamsIdSaveSendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsRunOnFireskyPreparePostRaw(
    requestParameters: ApiAiAgentsTeamsRunOnFireskyPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrepareResponseRunResp>> {
    if (requestParameters.runReq == null) {
      throw new runtime.RequiredError(
        "runReq",
        'Required parameter "runReq" was null or undefined when calling apiAiAgentsTeamsRunOnFireskyPreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/ai-agents-teams/run-on-firesky/prepare`;

    const response = await this.request(
      {
        body: RunReqToJSON(requestParameters.runReq),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrepareResponseRunRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsRunOnFireskyPreparePost(
    requestParameters: ApiAiAgentsTeamsRunOnFireskyPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrepareResponseRunResp> {
    const response = await this.apiAiAgentsTeamsRunOnFireskyPreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsRunOnFireskySendPostRaw(
    requestParameters: ApiAiAgentsTeamsRunOnFireskySendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (
      requestParameters.sendRequestBodyDeploySignedRunOnFireskyReqRunReqRunResp ==
      null
    ) {
      throw new runtime.RequiredError(
        "sendRequestBodyDeploySignedRunOnFireskyReqRunReqRunResp",
        'Required parameter "sendRequestBodyDeploySignedRunOnFireskyReqRunReqRunResp" was null or undefined when calling apiAiAgentsTeamsRunOnFireskySendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/ai-agents-teams/run-on-firesky/send`;

    const response = await this.request(
      {
        body: SendRequestBodyDeploySignedRunOnFireskyReqRunReqRunRespToJSON(
          requestParameters.sendRequestBodyDeploySignedRunOnFireskyReqRunReqRunResp,
        ),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async apiAiAgentsTeamsRunOnFireskySendPost(
    requestParameters: ApiAiAgentsTeamsRunOnFireskySendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.apiAiAgentsTeamsRunOnFireskySendPostRaw(
      requestParameters,
      initOverrides,
    );
  }

  /**
   */
  async apiAiAgentsTeamsRunPreparePostRaw(
    requestParameters: ApiAiAgentsTeamsRunPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrepareResponseRunResp>> {
    if (requestParameters.runReq == null) {
      throw new runtime.RequiredError(
        "runReq",
        'Required parameter "runReq" was null or undefined when calling apiAiAgentsTeamsRunPreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/ai-agents-teams/run/prepare`;

    const response = await this.request(
      {
        body: RunReqToJSON(requestParameters.runReq),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrepareResponseRunRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiAiAgentsTeamsRunPreparePost(
    requestParameters: ApiAiAgentsTeamsRunPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrepareResponseRunResp> {
    const response = await this.apiAiAgentsTeamsRunPreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiAiAgentsTeamsRunSendPostRaw(
    requestParameters: ApiAiAgentsTeamsRunSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<any>> {
    if (requestParameters.sendRequestBodySignedContractRunReqRunResp == null) {
      throw new runtime.RequiredError(
        "sendRequestBodySignedContractRunReqRunResp",
        'Required parameter "sendRequestBodySignedContractRunReqRunResp" was null or undefined when calling apiAiAgentsTeamsRunSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/ai-agents-teams/run/send`;

    const response = await this.request(
      {
        body: SendRequestBodySignedContractRunReqRunRespToJSON(
          requestParameters.sendRequestBodySignedContractRunReqRunResp,
        ),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get("content-type"))) {
      return new runtime.JSONApiResponse<any>(response);
    }
    return new runtime.TextApiResponse(response) as any;
  }

  /**
   */
  async apiAiAgentsTeamsRunSendPost(
    requestParameters: ApiAiAgentsTeamsRunSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<any> {
    const response = await this.apiAiAgentsTeamsRunSendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }
}
