/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  Address,
  CreateOslfReq,
  DeleteOslfResp,
  Oslf,
  Oslfs,
  PrepareResponseCreateOslfResp,
  PrepareResponseSaveOslfResp,
  SendRequestBodySignedContractCreateOslfReqCreateOslfResp,
  SendRequestBodySignedContractCreateOslfReqSaveOslfResp,
  SendResp,
  SignedContract,
} from "../models/index";

import {
  CreateOslfReqToJSON,
  DeleteOslfRespFromJSON,
  OslfFromJSON,
  OslfsFromJSON,
  PrepareResponseCreateOslfRespFromJSON,
  PrepareResponseSaveOslfRespFromJSON,
  SendRequestBodySignedContractCreateOslfReqCreateOslfRespToJSON,
  SendRequestBodySignedContractCreateOslfReqSaveOslfRespToJSON,
  SendRespFromJSON,
  SignedContractToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface ApiOslfAddressGetRequest {
  address: Address;
}

export interface ApiOslfAddressIdVersionsGetRequest {
  address: Address;
  id: string;
}

export interface ApiOslfAddressIdVersionsVersionGetRequest {
  address: Address;
  id: string;
  version: string;
}

export interface ApiOslfCreatePreparePostRequest {
  createOslfReq: CreateOslfReq;
}

export interface ApiOslfCreateSendPostRequest {
  sendRequestBodySignedContractCreateOslfReqCreateOslfResp: SendRequestBodySignedContractCreateOslfReqCreateOslfResp;
}

export interface ApiOslfIdDeletePreparePostRequest {
  id: string;
}

export interface ApiOslfIdDeleteSendPostRequest {
  id: string;
  signedContract: SignedContract;
}

export interface ApiOslfIdSavePreparePostRequest {
  createOslfReq: CreateOslfReq;
  id: string;
}

export interface ApiOslfIdSaveSendPostRequest {
  id: string;
  sendRequestBodySignedContractCreateOslfReqSaveOslfResp: SendRequestBodySignedContractCreateOslfReqSaveOslfResp;
}

/**
 *
 */
export class OslfApi extends runtime.BaseAPI {
  /**
   */
  async apiOslfAddressGetRaw(
    requestParameters: ApiOslfAddressGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Oslfs>> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiOslfAddressGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/oslf/{address}`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );

    const response = await this.request(
      {
        headers: headerParameters,
        method: "GET",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      OslfsFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfAddressGet(
    requestParameters: ApiOslfAddressGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Oslfs> {
    const response = await this.apiOslfAddressGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiOslfAddressIdVersionsGetRaw(
    requestParameters: ApiOslfAddressIdVersionsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Oslfs>> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiOslfAddressIdVersionsGet().',
      );
    }

    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiOslfAddressIdVersionsGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/oslf/{address}/{id}/versions`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        headers: headerParameters,
        method: "GET",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      OslfsFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfAddressIdVersionsGet(
    requestParameters: ApiOslfAddressIdVersionsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Oslfs> {
    const response = await this.apiOslfAddressIdVersionsGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiOslfAddressIdVersionsVersionGetRaw(
    requestParameters: ApiOslfAddressIdVersionsVersionGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Oslf>> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiOslfAddressIdVersionsVersionGet().',
      );
    }

    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiOslfAddressIdVersionsVersionGet().',
      );
    }

    if (requestParameters.version == null) {
      throw new runtime.RequiredError(
        "version",
        'Required parameter "version" was null or undefined when calling apiOslfAddressIdVersionsVersionGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/oslf/{address}/{id}/versions/{version}`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );
    urlPath = urlPath.replace(
      `{version}`,
      encodeURIComponent(String(requestParameters.version)),
    );

    const response = await this.request(
      {
        headers: headerParameters,
        method: "GET",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      OslfFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfAddressIdVersionsVersionGet(
    requestParameters: ApiOslfAddressIdVersionsVersionGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Oslf> {
    const response = await this.apiOslfAddressIdVersionsVersionGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiOslfCreatePreparePostRaw(
    requestParameters: ApiOslfCreatePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrepareResponseCreateOslfResp>> {
    if (requestParameters.createOslfReq == null) {
      throw new runtime.RequiredError(
        "createOslfReq",
        'Required parameter "createOslfReq" was null or undefined when calling apiOslfCreatePreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/oslf/create/prepare`;

    const response = await this.request(
      {
        body: CreateOslfReqToJSON(requestParameters.createOslfReq),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrepareResponseCreateOslfRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfCreatePreparePost(
    requestParameters: ApiOslfCreatePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrepareResponseCreateOslfResp> {
    const response = await this.apiOslfCreatePreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiOslfCreateSendPostRaw(
    requestParameters: ApiOslfCreateSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    if (
      requestParameters.sendRequestBodySignedContractCreateOslfReqCreateOslfResp ==
      null
    ) {
      throw new runtime.RequiredError(
        "sendRequestBodySignedContractCreateOslfReqCreateOslfResp",
        'Required parameter "sendRequestBodySignedContractCreateOslfReqCreateOslfResp" was null or undefined when calling apiOslfCreateSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/oslf/create/send`;

    const response = await this.request(
      {
        body: SendRequestBodySignedContractCreateOslfReqCreateOslfRespToJSON(
          requestParameters.sendRequestBodySignedContractCreateOslfReqCreateOslfResp,
        ),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfCreateSendPost(
    requestParameters: ApiOslfCreateSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response = await this.apiOslfCreateSendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiOslfIdDeletePreparePostRaw(
    requestParameters: ApiOslfIdDeletePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DeleteOslfResp>> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiOslfIdDeletePreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/oslf/{id}/delete/prepare`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DeleteOslfRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfIdDeletePreparePost(
    requestParameters: ApiOslfIdDeletePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DeleteOslfResp> {
    const response = await this.apiOslfIdDeletePreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiOslfIdDeleteSendPostRaw(
    requestParameters: ApiOslfIdDeleteSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiOslfIdDeleteSendPost().',
      );
    }

    if (requestParameters.signedContract == null) {
      throw new runtime.RequiredError(
        "signedContract",
        'Required parameter "signedContract" was null or undefined when calling apiOslfIdDeleteSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/oslf/{id}/delete/send`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        body: SignedContractToJSON(requestParameters.signedContract),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfIdDeleteSendPost(
    requestParameters: ApiOslfIdDeleteSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response = await this.apiOslfIdDeleteSendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiOslfIdSavePreparePostRaw(
    requestParameters: ApiOslfIdSavePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrepareResponseSaveOslfResp>> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiOslfIdSavePreparePost().',
      );
    }

    if (requestParameters.createOslfReq == null) {
      throw new runtime.RequiredError(
        "createOslfReq",
        'Required parameter "createOslfReq" was null or undefined when calling apiOslfIdSavePreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/oslf/{id}/save/prepare`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        body: CreateOslfReqToJSON(requestParameters.createOslfReq),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrepareResponseSaveOslfRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfIdSavePreparePost(
    requestParameters: ApiOslfIdSavePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrepareResponseSaveOslfResp> {
    const response = await this.apiOslfIdSavePreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   */
  async apiOslfIdSaveSendPostRaw(
    requestParameters: ApiOslfIdSaveSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiOslfIdSaveSendPost().',
      );
    }

    if (
      requestParameters.sendRequestBodySignedContractCreateOslfReqSaveOslfResp ==
      null
    ) {
      throw new runtime.RequiredError(
        "sendRequestBodySignedContractCreateOslfReqSaveOslfResp",
        'Required parameter "sendRequestBodySignedContractCreateOslfReqSaveOslfResp" was null or undefined when calling apiOslfIdSaveSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/oslf/{id}/save/send`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    const response = await this.request(
      {
        body: SendRequestBodySignedContractCreateOslfReqSaveOslfRespToJSON(
          requestParameters.sendRequestBodySignedContractCreateOslfReqSaveOslfResp,
        ),
        headers: headerParameters,
        method: "POST",
        path: urlPath,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfIdSaveSendPost(
    requestParameters: ApiOslfIdSaveSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response = await this.apiOslfIdSaveSendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }
}
