/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  Address,
  CreateOslfReq,
  DeleteOslfResp,
  Oslf,
  Oslfs,
  PrepareResponseCreateOslfResp,
  PrepareResponseSaveOslfResp,
  SendRequestBodySignedContractCreateOslfReqCreateOslfResp,
  SendRequestBodySignedContractCreateOslfReqSaveOslfResp,
  SendResp,
  SignedContract,
} from "../models/index";

import {
  CreateOslfReqToJSON,
  DeleteOslfRespFromJSON,
  OslfFromJSON,
  OslfsFromJSON,
  PrepareResponseCreateOslfRespFromJSON,
  PrepareResponseSaveOslfRespFromJSON,
  SendRequestBodySignedContractCreateOslfReqCreateOslfRespToJSON,
  SendRequestBodySignedContractCreateOslfReqSaveOslfRespToJSON,
  SendRespFromJSON,
  SignedContractToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface ApiOslfsAddressGetRequest {
  address: Address;
}

export interface ApiOslfsAddressIdVersionsGetRequest {
  address: Address;
  id: string;
}

export interface ApiOslfsAddressIdVersionsVersionGetRequest {
  address: Address;
  id: string;
  version: string;
}

export interface ApiOslfsCreatePreparePostRequest {
  createOslfReq: CreateOslfReq;
}

export interface ApiOslfsCreateSendPostRequest {
  sendRequestBodySignedContractCreateOslfReqCreateOslfResp: SendRequestBodySignedContractCreateOslfReqCreateOslfResp;
}

export interface ApiOslfsIdDeletePreparePostRequest {
  id: string;
}

export interface ApiOslfsIdDeleteSendPostRequest {
  id: string;
  signedContract: SignedContract;
}

export interface ApiOslfsIdSavePreparePostRequest {
  createOslfReq: CreateOslfReq;
  id: string;
}

export interface ApiOslfsIdSaveSendPostRequest {
  id: string;
  sendRequestBodySignedContractCreateOslfReqSaveOslfResp: SendRequestBodySignedContractCreateOslfReqSaveOslfResp;
}

/**
 *
 */
export class OslfsApi extends runtime.BaseAPI {
  /**
   * Creates request options for apiOslfsAddressGet without sending the request
   */
  async apiOslfsAddressGetRequestOpts(
    requestParameters: ApiOslfsAddressGetRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiOslfsAddressGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/oslfs/{address}`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );

    return {
      headers: headerParameters,
      method: "GET",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiOslfsAddressGetRaw(
    requestParameters: ApiOslfsAddressGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Oslfs>> {
    const requestOptions =
      await this.apiOslfsAddressGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      OslfsFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfsAddressGet(
    requestParameters: ApiOslfsAddressGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Oslfs> {
    const response = await this.apiOslfsAddressGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   * Creates request options for apiOslfsAddressIdVersionsGet without sending the request
   */
  async apiOslfsAddressIdVersionsGetRequestOpts(
    requestParameters: ApiOslfsAddressIdVersionsGetRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiOslfsAddressIdVersionsGet().',
      );
    }

    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiOslfsAddressIdVersionsGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/oslfs/{address}/{id}/versions`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    return {
      headers: headerParameters,
      method: "GET",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiOslfsAddressIdVersionsGetRaw(
    requestParameters: ApiOslfsAddressIdVersionsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Oslfs>> {
    const requestOptions =
      await this.apiOslfsAddressIdVersionsGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      OslfsFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfsAddressIdVersionsGet(
    requestParameters: ApiOslfsAddressIdVersionsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Oslfs> {
    const response = await this.apiOslfsAddressIdVersionsGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   * Creates request options for apiOslfsAddressIdVersionsVersionGet without sending the request
   */
  async apiOslfsAddressIdVersionsVersionGetRequestOpts(
    requestParameters: ApiOslfsAddressIdVersionsVersionGetRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiOslfsAddressIdVersionsVersionGet().',
      );
    }

    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiOslfsAddressIdVersionsVersionGet().',
      );
    }

    if (requestParameters.version == null) {
      throw new runtime.RequiredError(
        "version",
        'Required parameter "version" was null or undefined when calling apiOslfsAddressIdVersionsVersionGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/oslfs/{address}/{id}/versions/{version}`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );
    urlPath = urlPath.replace(
      `{version}`,
      encodeURIComponent(String(requestParameters.version)),
    );

    return {
      headers: headerParameters,
      method: "GET",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiOslfsAddressIdVersionsVersionGetRaw(
    requestParameters: ApiOslfsAddressIdVersionsVersionGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Oslf>> {
    const requestOptions =
      await this.apiOslfsAddressIdVersionsVersionGetRequestOpts(
        requestParameters,
      );
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      OslfFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfsAddressIdVersionsVersionGet(
    requestParameters: ApiOslfsAddressIdVersionsVersionGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Oslf> {
    const response = await this.apiOslfsAddressIdVersionsVersionGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   * Creates request options for apiOslfsCreatePreparePost without sending the request
   */
  async apiOslfsCreatePreparePostRequestOpts(
    requestParameters: ApiOslfsCreatePreparePostRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters.createOslfReq == null) {
      throw new runtime.RequiredError(
        "createOslfReq",
        'Required parameter "createOslfReq" was null or undefined when calling apiOslfsCreatePreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/oslfs/create/prepare`;

    return {
      body: CreateOslfReqToJSON(requestParameters.createOslfReq),
      headers: headerParameters,
      method: "POST",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiOslfsCreatePreparePostRaw(
    requestParameters: ApiOslfsCreatePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrepareResponseCreateOslfResp>> {
    const requestOptions =
      await this.apiOslfsCreatePreparePostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrepareResponseCreateOslfRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfsCreatePreparePost(
    requestParameters: ApiOslfsCreatePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrepareResponseCreateOslfResp> {
    const response = await this.apiOslfsCreatePreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   * Creates request options for apiOslfsCreateSendPost without sending the request
   */
  async apiOslfsCreateSendPostRequestOpts(
    requestParameters: ApiOslfsCreateSendPostRequest,
  ): Promise<runtime.RequestOpts> {
    if (
      requestParameters.sendRequestBodySignedContractCreateOslfReqCreateOslfResp ==
      null
    ) {
      throw new runtime.RequiredError(
        "sendRequestBodySignedContractCreateOslfReqCreateOslfResp",
        'Required parameter "sendRequestBodySignedContractCreateOslfReqCreateOslfResp" was null or undefined when calling apiOslfsCreateSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/oslfs/create/send`;

    return {
      body: SendRequestBodySignedContractCreateOslfReqCreateOslfRespToJSON(
        requestParameters.sendRequestBodySignedContractCreateOslfReqCreateOslfResp,
      ),
      headers: headerParameters,
      method: "POST",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiOslfsCreateSendPostRaw(
    requestParameters: ApiOslfsCreateSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    const requestOptions =
      await this.apiOslfsCreateSendPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfsCreateSendPost(
    requestParameters: ApiOslfsCreateSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response = await this.apiOslfsCreateSendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   * Creates request options for apiOslfsIdDeletePreparePost without sending the request
   */
  async apiOslfsIdDeletePreparePostRequestOpts(
    requestParameters: ApiOslfsIdDeletePreparePostRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiOslfsIdDeletePreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/oslfs/{id}/delete/prepare`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    return {
      headers: headerParameters,
      method: "POST",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiOslfsIdDeletePreparePostRaw(
    requestParameters: ApiOslfsIdDeletePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<DeleteOslfResp>> {
    const requestOptions =
      await this.apiOslfsIdDeletePreparePostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      DeleteOslfRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfsIdDeletePreparePost(
    requestParameters: ApiOslfsIdDeletePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<DeleteOslfResp> {
    const response = await this.apiOslfsIdDeletePreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   * Creates request options for apiOslfsIdDeleteSendPost without sending the request
   */
  async apiOslfsIdDeleteSendPostRequestOpts(
    requestParameters: ApiOslfsIdDeleteSendPostRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiOslfsIdDeleteSendPost().',
      );
    }

    if (requestParameters.signedContract == null) {
      throw new runtime.RequiredError(
        "signedContract",
        'Required parameter "signedContract" was null or undefined when calling apiOslfsIdDeleteSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/oslfs/{id}/delete/send`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    return {
      body: SignedContractToJSON(requestParameters.signedContract),
      headers: headerParameters,
      method: "POST",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiOslfsIdDeleteSendPostRaw(
    requestParameters: ApiOslfsIdDeleteSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    const requestOptions =
      await this.apiOslfsIdDeleteSendPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfsIdDeleteSendPost(
    requestParameters: ApiOslfsIdDeleteSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response = await this.apiOslfsIdDeleteSendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   * Creates request options for apiOslfsIdSavePreparePost without sending the request
   */
  async apiOslfsIdSavePreparePostRequestOpts(
    requestParameters: ApiOslfsIdSavePreparePostRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiOslfsIdSavePreparePost().',
      );
    }

    if (requestParameters.createOslfReq == null) {
      throw new runtime.RequiredError(
        "createOslfReq",
        'Required parameter "createOslfReq" was null or undefined when calling apiOslfsIdSavePreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/oslfs/{id}/save/prepare`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    return {
      body: CreateOslfReqToJSON(requestParameters.createOslfReq),
      headers: headerParameters,
      method: "POST",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiOslfsIdSavePreparePostRaw(
    requestParameters: ApiOslfsIdSavePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrepareResponseSaveOslfResp>> {
    const requestOptions =
      await this.apiOslfsIdSavePreparePostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrepareResponseSaveOslfRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfsIdSavePreparePost(
    requestParameters: ApiOslfsIdSavePreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrepareResponseSaveOslfResp> {
    const response = await this.apiOslfsIdSavePreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   * Creates request options for apiOslfsIdSaveSendPost without sending the request
   */
  async apiOslfsIdSaveSendPostRequestOpts(
    requestParameters: ApiOslfsIdSaveSendPostRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters.id == null) {
      throw new runtime.RequiredError(
        "id",
        'Required parameter "id" was null or undefined when calling apiOslfsIdSaveSendPost().',
      );
    }

    if (
      requestParameters.sendRequestBodySignedContractCreateOslfReqSaveOslfResp ==
      null
    ) {
      throw new runtime.RequiredError(
        "sendRequestBodySignedContractCreateOslfReqSaveOslfResp",
        'Required parameter "sendRequestBodySignedContractCreateOslfReqSaveOslfResp" was null or undefined when calling apiOslfsIdSaveSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    let urlPath = `/api/oslfs/{id}/save/send`;
    urlPath = urlPath.replace(
      `{id}`,
      encodeURIComponent(String(requestParameters.id)),
    );

    return {
      body: SendRequestBodySignedContractCreateOslfReqSaveOslfRespToJSON(
        requestParameters.sendRequestBodySignedContractCreateOslfReqSaveOslfResp,
      ),
      headers: headerParameters,
      method: "POST",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiOslfsIdSaveSendPostRaw(
    requestParameters: ApiOslfsIdSaveSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    const requestOptions =
      await this.apiOslfsIdSaveSendPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiOslfsIdSaveSendPost(
    requestParameters: ApiOslfsIdSaveSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response = await this.apiOslfsIdSaveSendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }
}
