/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type {
  Address,
  BoostReq,
  PrepareResponseBoostResp,
  PrepareResponseTransferResp,
  SendRequestBodySignedContractBoostReqBoostResp,
  SendRequestBodySignedContractTransferReqTransferResp,
  SendResp,
  TransferReq,
  WalletStateAndHistory,
} from "../models/index";

import {
  BoostReqToJSON,
  PrepareResponseBoostRespFromJSON,
  PrepareResponseTransferRespFromJSON,
  SendRequestBodySignedContractBoostReqBoostRespToJSON,
  SendRequestBodySignedContractTransferReqTransferRespToJSON,
  SendRespFromJSON,
  TransferReqToJSON,
  WalletStateAndHistoryFromJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface ApiWalletsAddressDeploysGetRequest {
  address: Address;
}

export interface ApiWalletsAddressStateGetRequest {
  address: Address;
}

export interface ApiWalletsBoostPreparePostRequest {
  boostReq: BoostReq;
}

export interface ApiWalletsBoostSendPostRequest {
  sendRequestBodySignedContractBoostReqBoostResp: SendRequestBodySignedContractBoostReqBoostResp;
}

export interface ApiWalletsTransferPreparePostRequest {
  transferReq: TransferReq;
}

export interface ApiWalletsTransferSendPostRequest {
  sendRequestBodySignedContractTransferReqTransferResp: SendRequestBodySignedContractTransferReqTransferResp;
}

/**
 *
 */
export class WalletsApi extends runtime.BaseAPI {
  /**
   * Creates request options for apiWalletsAddressDeploysGet without sending the request
   */
  async apiWalletsAddressDeploysGetRequestOpts(
    requestParameters: ApiWalletsAddressDeploysGetRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiWalletsAddressDeploysGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/wallets/{address}/deploys`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );

    return {
      headers: headerParameters,
      method: "GET",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiWalletsAddressDeploysGetRaw(
    requestParameters: ApiWalletsAddressDeploysGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    const requestOptions =
      await this.apiWalletsAddressDeploysGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async apiWalletsAddressDeploysGet(
    requestParameters: ApiWalletsAddressDeploysGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.apiWalletsAddressDeploysGetRaw(requestParameters, initOverrides);
  }

  /**
   * Creates request options for apiWalletsAddressStateGet without sending the request
   */
  async apiWalletsAddressStateGetRequestOpts(
    requestParameters: ApiWalletsAddressStateGetRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters.address == null) {
      throw new runtime.RequiredError(
        "address",
        'Required parameter "address" was null or undefined when calling apiWalletsAddressStateGet().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    let urlPath = `/api/wallets/{address}/state`;
    urlPath = urlPath.replace(
      `{address}`,
      encodeURIComponent(String(requestParameters.address)),
    );

    return {
      headers: headerParameters,
      method: "GET",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiWalletsAddressStateGetRaw(
    requestParameters: ApiWalletsAddressStateGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<WalletStateAndHistory>> {
    const requestOptions =
      await this.apiWalletsAddressStateGetRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      WalletStateAndHistoryFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiWalletsAddressStateGet(
    requestParameters: ApiWalletsAddressStateGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<WalletStateAndHistory> {
    const response = await this.apiWalletsAddressStateGetRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   * Creates request options for apiWalletsBoostPreparePost without sending the request
   */
  async apiWalletsBoostPreparePostRequestOpts(
    requestParameters: ApiWalletsBoostPreparePostRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters.boostReq == null) {
      throw new runtime.RequiredError(
        "boostReq",
        'Required parameter "boostReq" was null or undefined when calling apiWalletsBoostPreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/wallets/boost/prepare`;

    return {
      body: BoostReqToJSON(requestParameters.boostReq),
      headers: headerParameters,
      method: "POST",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiWalletsBoostPreparePostRaw(
    requestParameters: ApiWalletsBoostPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrepareResponseBoostResp>> {
    const requestOptions =
      await this.apiWalletsBoostPreparePostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrepareResponseBoostRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiWalletsBoostPreparePost(
    requestParameters: ApiWalletsBoostPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrepareResponseBoostResp> {
    const response = await this.apiWalletsBoostPreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   * Creates request options for apiWalletsBoostSendPost without sending the request
   */
  async apiWalletsBoostSendPostRequestOpts(
    requestParameters: ApiWalletsBoostSendPostRequest,
  ): Promise<runtime.RequestOpts> {
    if (
      requestParameters.sendRequestBodySignedContractBoostReqBoostResp == null
    ) {
      throw new runtime.RequiredError(
        "sendRequestBodySignedContractBoostReqBoostResp",
        'Required parameter "sendRequestBodySignedContractBoostReqBoostResp" was null or undefined when calling apiWalletsBoostSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/wallets/boost/send`;

    return {
      body: SendRequestBodySignedContractBoostReqBoostRespToJSON(
        requestParameters.sendRequestBodySignedContractBoostReqBoostResp,
      ),
      headers: headerParameters,
      method: "POST",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiWalletsBoostSendPostRaw(
    requestParameters: ApiWalletsBoostSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    const requestOptions =
      await this.apiWalletsBoostSendPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiWalletsBoostSendPost(
    requestParameters: ApiWalletsBoostSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response = await this.apiWalletsBoostSendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   * Creates request options for apiWalletsTransferPreparePost without sending the request
   */
  async apiWalletsTransferPreparePostRequestOpts(
    requestParameters: ApiWalletsTransferPreparePostRequest,
  ): Promise<runtime.RequestOpts> {
    if (requestParameters.transferReq == null) {
      throw new runtime.RequiredError(
        "transferReq",
        'Required parameter "transferReq" was null or undefined when calling apiWalletsTransferPreparePost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/wallets/transfer/prepare`;

    return {
      body: TransferReqToJSON(requestParameters.transferReq),
      headers: headerParameters,
      method: "POST",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiWalletsTransferPreparePostRaw(
    requestParameters: ApiWalletsTransferPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<PrepareResponseTransferResp>> {
    const requestOptions =
      await this.apiWalletsTransferPreparePostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      PrepareResponseTransferRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiWalletsTransferPreparePost(
    requestParameters: ApiWalletsTransferPreparePostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<PrepareResponseTransferResp> {
    const response = await this.apiWalletsTransferPreparePostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }

  /**
   * Creates request options for apiWalletsTransferSendPost without sending the request
   */
  async apiWalletsTransferSendPostRequestOpts(
    requestParameters: ApiWalletsTransferSendPostRequest,
  ): Promise<runtime.RequestOpts> {
    if (
      requestParameters.sendRequestBodySignedContractTransferReqTransferResp ==
      null
    ) {
      throw new runtime.RequiredError(
        "sendRequestBodySignedContractTransferReqTransferResp",
        'Required parameter "sendRequestBodySignedContractTransferReqTransferResp" was null or undefined when calling apiWalletsTransferSendPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json; charset=utf-8";

    const urlPath = `/api/wallets/transfer/send`;

    return {
      body: SendRequestBodySignedContractTransferReqTransferRespToJSON(
        requestParameters.sendRequestBodySignedContractTransferReqTransferResp,
      ),
      headers: headerParameters,
      method: "POST",
      path: urlPath,
      query: queryParameters,
    };
  }

  /**
   */
  async apiWalletsTransferSendPostRaw(
    requestParameters: ApiWalletsTransferSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<SendResp>> {
    const requestOptions =
      await this.apiWalletsTransferSendPostRequestOpts(requestParameters);
    const response = await this.request(requestOptions, initOverrides);

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      SendRespFromJSON(jsonValue),
    );
  }

  /**
   */
  async apiWalletsTransferSendPost(
    requestParameters: ApiWalletsTransferSendPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<SendResp> {
    const response = await this.apiWalletsTransferSendPostRaw(
      requestParameters,
      initOverrides,
    );
    return response.value();
  }
}
