declare const classNames: {
  readonly page: "page";
  readonly headerBar: "headerBar";
  readonly appTitle: "appTitle";
  readonly mainContent: "mainContent";
  readonly dashboard: "dashboard";
  readonly dashboardTop: "dashboardTop";
  readonly agentsButton: "agentsButton";
  readonly contentArea: "contentArea";
  readonly contentHeader: "contentHeader";
  readonly gridContainer: "gridContainer";
  readonly gridBox: "gridBox";
  readonly createBox: "createBox";
  readonly robotIcon: "robotIcon";
  readonly smallRobotIcon: "smallRobotIcon";
  readonly dashboardColumn: "dashboardColumn";
  readonly dashboardDivider: "dashboardDivider";
  readonly dashboardButtons: "dashboardButtons";
  readonly iconButton: "iconButton";
};
export = classNames;
