declare const classNames: {
  readonly "app-title": "app-title";
  readonly chevron: "chevron";
  readonly "content-area": "content-area";
  readonly "content-header": "content-header";
  readonly dashboard: "dashboard";
  readonly "dashboard-buttons": "dashboard-buttons";
  readonly "dashboard-column": "dashboard-column";
  readonly "dashboard-divider": "dashboard-divider";
  readonly "dashboard-top": "dashboard-top";
  readonly dropdown: "dropdown";
  readonly entered: "entered";
  readonly entering: "entering";
  readonly "grid-container": "grid-container";
  readonly "header-bar": "header-bar";
  readonly "header-right": "header-right";
  readonly "language-dropdown": "language-dropdown";
  readonly "main-content": "main-content";
  readonly page: "page";
  readonly "settings-icon": "settings-icon";
  readonly "tab-content": "tab-content";
};
export default classNames;
