/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TimestampMillis } from "./TimestampMillis";
import type { Uri } from "./Uri";

import {
  TimestampMillisFromJSON,
  TimestampMillisToJSON,
} from "./TimestampMillis";
import { UriFromJSON, UriToJSON } from "./Uri";

/**
 *
 * @export
 * @interface AgentsTeamHeader
 */
export interface AgentsTeamHeader {
  /**
   *
   * @type {TimestampMillis}
   * @memberof AgentsTeamHeader
   */
  createdAt: TimestampMillis;
  /**
   *
   * @type {string}
   * @memberof AgentsTeamHeader
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeamHeader
   */
  id: string;
  /**
   *
   * @type {TimestampMillis}
   * @memberof AgentsTeamHeader
   */
  lastDeploy?: TimestampMillis;
  /**
   *
   * @type {string}
   * @memberof AgentsTeamHeader
   */
  logo?: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeamHeader
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeamHeader
   */
  shard?: string;
  /**
   *
   * @type {Uri}
   * @memberof AgentsTeamHeader
   */
  uri?: Uri;
  /**
   *
   * @type {string}
   * @memberof AgentsTeamHeader
   */
  version: string;
}

/**
 * Check if a given object implements the AgentsTeamHeader interface.
 */
export function instanceOfAgentsTeamHeader(
  value: object,
): value is AgentsTeamHeader {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("createdAt" in value) || value.createdAt === undefined) {
    return false;
  }
  if (!("name" in value) || value.name === undefined) {
    return false;
  }
  return true;
}

export function AgentsTeamHeaderFromJSON(json: any): AgentsTeamHeader {
  return AgentsTeamHeaderFromJSONTyped(json, false);
}

export function AgentsTeamHeaderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AgentsTeamHeader {
  if (json == null) {
    return json;
  }
  return {
    createdAt: TimestampMillisFromJSON(json.created_at),
    description: json.description == null ? undefined : json.description,
    id: json.id,
    lastDeploy:
      json.last_deploy == null
        ? undefined
        : TimestampMillisFromJSON(json.last_deploy),
    logo: json.logo == null ? undefined : json.logo,
    name: json.name,
    shard: json.shard == null ? undefined : json.shard,
    uri: json.uri == null ? undefined : UriFromJSON(json.uri),
    version: json.version,
  };
}

export function AgentsTeamHeaderToJSON(json: any): AgentsTeamHeader {
  return AgentsTeamHeaderToJSONTyped(json, false);
}

export function AgentsTeamHeaderToJSONTyped(
  value?: AgentsTeamHeader | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    created_at: TimestampMillisToJSON(value.createdAt),
    description: value.description,
    id: value.id,
    last_deploy: TimestampMillisToJSON(value.lastDeploy),
    logo: value.logo,
    name: value.name,
    shard: value.shard,
    uri: UriToJSON(value.uri),
    version: value.version,
  };
}
