/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface AgentsTeam
 */
export interface AgentsTeam {
  /**
   *
   * @type {string}
   * @memberof AgentsTeam
   */
  graph?: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeam
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeam
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeam
   */
  shard?: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeam
   */
  version: string;
}

/**
 * Check if a given object implements the AgentsTeam interface.
 */
export function instanceOfAgentsTeam(value: object): value is AgentsTeam {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("name" in value) || value.name === undefined) {
    return false;
  }
  return true;
}

export function AgentsTeamFromJSON(json: any): AgentsTeam {
  return AgentsTeamFromJSONTyped(json, false);
}

export function AgentsTeamFromJSONTyped(json: any, _ignoreDiscriminator: boolean): AgentsTeam {
  if (json == null) {
    return json;
  }
  return {
    graph: json.graph == null ? undefined : json.graph,
    id: json.id,
    name: json.name,
    shard: json.shard == null ? undefined : json.shard,
    version: json.version,
  };
}

export function AgentsTeamToJSON(json: any): AgentsTeam {
  return AgentsTeamToJSONTyped(json, false);
}

export function AgentsTeamToJSONTyped(
  value?: AgentsTeam | null,
  _ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    graph: value.graph,
    id: value.id,
    name: value.name,
    shard: value.shard,
    version: value.version,
  };
}
