/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TimestampMillis } from "./TimestampMillis";

import {
  TimestampMillisFromJSON,
  TimestampMillisToJSON,
} from "./TimestampMillis";

/**
 *
 * @export
 * @interface AgentsTeamHeader
 */
export interface AgentsTeamHeader {
  /**
   *
   * @type {TimestampMillis}
   * @memberof AgentsTeamHeader
   */
  createdAt: TimestampMillis;
  /**
   *
   * @type {string}
   * @memberof AgentsTeamHeader
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeamHeader
   */
  logo?: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeamHeader
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeamHeader
   */
  shard?: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeamHeader
   */
  version: string;
}

/**
 * Check if a given object implements the AgentsTeamHeader interface.
 */
export function instanceOfAgentsTeamHeader(
  value: object,
): value is AgentsTeamHeader {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("createdAt" in value) || value.createdAt === undefined) {
    return false;
  }
  if (!("name" in value) || value.name === undefined) {
    return false;
  }
  return true;
}

export function AgentsTeamHeaderFromJSON(json: any): AgentsTeamHeader {
  return AgentsTeamHeaderFromJSONTyped(json, false);
}

export function AgentsTeamHeaderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AgentsTeamHeader {
  if (json == null) {
    return json;
  }
  return {
    createdAt: TimestampMillisFromJSON(json.created_at),
    id: json.id,
    logo: json.logo == null ? undefined : json.logo,
    name: json.name,
    shard: json.shard == null ? undefined : json.shard,
    version: json.version,
  };
}

export function AgentsTeamHeaderToJSON(json: any): AgentsTeamHeader {
  return AgentsTeamHeaderToJSONTyped(json, false);
}

export function AgentsTeamHeaderToJSONTyped(
  value?: AgentsTeamHeader | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    created_at: TimestampMillisToJSON(value.createdAt),
    id: value.id,
    logo: value.logo,
    name: value.name,
    shard: value.shard,
    version: value.version,
  };
}
