/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Graph } from "./Graph";
import type { TimestampMillis } from "./TimestampMillis";

import { GraphFromJSON, GraphToJSON } from "./Graph";
import {
  TimestampMillisFromJSON,
  TimestampMillisToJSON,
} from "./TimestampMillis";

/**
 *
 * @export
 * @interface AgentsTeam
 */
export interface AgentsTeam {
  /**
   *
   * @type {TimestampMillis}
   * @memberof AgentsTeam
   */
  createdAt: TimestampMillis;
  /**
   *
   * @type {string}
   * @memberof AgentsTeam
   */
  description?: string;
  /**
   *
   * @type {Graph}
   * @memberof AgentsTeam
   */
  graph?: Graph;
  /**
   *
   * @type {string}
   * @memberof AgentsTeam
   */
  id: string;
  /**
   *
   * @type {TimestampMillis}
   * @memberof AgentsTeam
   */
  lastDeploy?: TimestampMillis;
  /**
   *
   * @type {string}
   * @memberof AgentsTeam
   */
  logo?: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeam
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeam
   */
  shard?: string;
  /**
   *
   * @type {string}
   * @memberof AgentsTeam
   */
  version: string;
}

/**
 * Check if a given object implements the AgentsTeam interface.
 */
export function instanceOfAgentsTeam(value: object): value is AgentsTeam {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("createdAt" in value) || value.createdAt === undefined) {
    return false;
  }
  if (!("name" in value) || value.name === undefined) {
    return false;
  }
  return true;
}

export function AgentsTeamFromJSON(json: any): AgentsTeam {
  return AgentsTeamFromJSONTyped(json, false);
}

export function AgentsTeamFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): AgentsTeam {
  if (json == null) {
    return json;
  }
  return {
    createdAt: TimestampMillisFromJSON(json.created_at),
    description: json.description == null ? undefined : json.description,
    graph: json.graph == null ? undefined : GraphFromJSON(json.graph),
    id: json.id,
    lastDeploy:
      json.last_deploy == null
        ? undefined
        : TimestampMillisFromJSON(json.last_deploy),
    logo: json.logo == null ? undefined : json.logo,
    name: json.name,
    shard: json.shard == null ? undefined : json.shard,
    version: json.version,
  };
}

export function AgentsTeamToJSON(json: any): AgentsTeam {
  return AgentsTeamToJSONTyped(json, false);
}

export function AgentsTeamToJSONTyped(
  value?: AgentsTeam | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    created_at: TimestampMillisToJSON(value.createdAt),
    description: value.description,
    graph: GraphToJSON(value.graph),
    id: value.id,
    last_deploy: TimestampMillisToJSON(value.lastDeploy),
    logo: value.logo,
    name: value.name,
    shard: value.shard,
    version: value.version,
  };
}
