/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface Agent
 */
export interface Agent {
  /**
   *
   * @type {string}
   * @memberof Agent
   */
  code?: string;
  /**
   *
   * @type {string}
   * @memberof Agent
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Agent
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof Agent
   */
  shard?: string;
  /**
   *
   * @type {string}
   * @memberof Agent
   */
  version: string;
}

/**
 * Check if a given object implements the Agent interface.
 */
export function instanceOfAgent(value: object): value is Agent {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("name" in value) || value.name === undefined) {
    return false;
  }
  return true;
}

export function AgentFromJSON(json: any): Agent {
  return AgentFromJSONTyped(json, false);
}

export function AgentFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Agent {
  if (json == null) {
    return json;
  }
  return {
    code: json.code == null ? undefined : json.code,
    id: json.id,
    name: json.name,
    shard: json.shard == null ? undefined : json.shard,
    version: json.version,
  };
}

export function AgentToJSON(json: any): Agent {
  return AgentToJSONTyped(json, false);
}

export function AgentToJSONTyped(
  value?: Agent | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    code: value.code,
    id: value.id,
    name: value.name,
    shard: value.shard,
    version: value.version,
  };
}
