/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Graph } from "./Graph";
import { GraphFromJSON, GraphToJSON } from "./Graph";
import type { Vertex } from "./Vertex";
import { VertexFromJSON, VertexToJSON } from "./Vertex";

/**
 *
 * @export
 * @interface Binding
 */
export interface Binding {
  /**
   *
   * @type {string}
   * @memberof Binding
   */
  _var: string;
  /**
   *
   * @type {Graph}
   * @memberof Binding
   */
  graph: Graph;
  /**
   *
   * @type {Vertex}
   * @memberof Binding
   */
  vertex: Vertex;
}

/**
 * Check if a given object implements the Binding interface.
 */
export function instanceOfBinding(value: object): value is Binding {
  if (!("graph" in value) || value.graph === undefined) {
    return false;
  }
  if (!("_var" in value) || value._var === undefined) {
    return false;
  }
  if (!("vertex" in value) || value.vertex === undefined) {
    return false;
  }
  return true;
}

export function BindingFromJSON(json: any): Binding {
  return BindingFromJSONTyped(json, false);
}

export function BindingFromJSONTyped(json: any, ignoreDiscriminator: boolean): Binding {
  if (json == null) {
    return json;
  }
  return {
    _var: json.var,
    graph: GraphFromJSON(json.graph),
    vertex: VertexFromJSON(json.vertex),
  };
}

export function BindingToJSON(json: any): Binding {
  return BindingToJSONTyped(json, false);
}

export function BindingToJSONTyped(
  value?: Binding | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    graph: GraphToJSON(value.graph),
    var: value._var,
    vertex: VertexToJSON(value.vertex),
  };
}
