/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Direction } from "./Direction";
import type { Int64 } from "./Int64";
import type { UnixTimestamp } from "./UnixTimestamp";

import { DirectionFromJSON, DirectionToJSON } from "./Direction";
import { Int64FromJSON, Int64ToJSON } from "./Int64";
import { UnixTimestampFromJSON, UnixTimestampToJSON } from "./UnixTimestamp";

/**
 *
 * @export
 * @interface Boost
 */
export interface Boost {
  /**
   *
   * @type {Int64}
   * @memberof Boost
   */
  amount: Int64;
  /**
   *
   * @type {UnixTimestamp}
   * @memberof Boost
   */
  date: UnixTimestamp;
  /**
   *
   * @type {Direction}
   * @memberof Boost
   */
  direction: Direction;
  /**
   *
   * @type {string}
   * @memberof Boost
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Boost
   */
  post: string;
  /**
   *
   * @type {string}
   * @memberof Boost
   */
  username: string;
}

/**
 * Check if a given object implements the Boost interface.
 */
export function instanceOfBoost(value: object): value is Boost {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("username" in value) || value.username === undefined) {
    return false;
  }
  if (!("direction" in value) || value.direction === undefined) {
    return false;
  }
  if (!("date" in value) || value.date === undefined) {
    return false;
  }
  if (!("amount" in value) || value.amount === undefined) {
    return false;
  }
  if (!("post" in value) || value.post === undefined) {
    return false;
  }
  return true;
}

export function BoostFromJSON(json: any): Boost {
  return BoostFromJSONTyped(json, false);
}

export function BoostFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Boost {
  if (json == null) {
    return json;
  }
  return {
    amount: Int64FromJSON(json.amount),
    date: UnixTimestampFromJSON(json.date),
    direction: DirectionFromJSON(json.direction),
    id: json.id,
    post: json.post,
    username: json.username,
  };
}

export function BoostToJSON(json: any): Boost {
  return BoostToJSONTyped(json, false);
}

export function BoostToJSONTyped(
  value?: Boost | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amount: Int64ToJSON(value.amount),
    date: UnixTimestampToJSON(value.date),
    direction: DirectionToJSON(value.direction),
    id: value.id,
    post: value.post,
    username: value.username,
  };
}
