/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Address } from "./Address";
import type { Int64 } from "./Int64";

import { AddressFromJSON, AddressToJSON } from "./Address";
import { Int64FromJSON, Int64ToJSON } from "./Int64";

/**
 *
 * @export
 * @interface BoostReq
 */
export interface BoostReq {
  /**
   *
   * @type {Int64}
   * @memberof BoostReq
   */
  amount: Int64;
  /**
   *
   * @type {string}
   * @memberof BoostReq
   */
  description?: string;
  /**
   *
   * @type {Address}
   * @memberof BoostReq
   */
  from: Address;
  /**
   *
   * @type {string}
   * @memberof BoostReq
   */
  post?: string;
  /**
   *
   * @type {Address}
   * @memberof BoostReq
   */
  to: Address;
}

/**
 * Check if a given object implements the BoostReq interface.
 */
export function instanceOfBoostReq(value: object): value is BoostReq {
  if (!("from" in value) || value.from === undefined) {
    return false;
  }
  if (!("to" in value) || value.to === undefined) {
    return false;
  }
  if (!("amount" in value) || value.amount === undefined) {
    return false;
  }
  return true;
}

export function BoostReqFromJSON(json: any): BoostReq {
  return BoostReqFromJSONTyped(json, false);
}

export function BoostReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BoostReq {
  if (json == null) {
    return json;
  }
  return {
    amount: Int64FromJSON(json.amount),
    description: json.description == null ? undefined : json.description,
    from: AddressFromJSON(json.from),
    post: json.post == null ? undefined : json.post,
    to: AddressFromJSON(json.to),
  };
}

export function BoostReqToJSON(json: any): BoostReq {
  return BoostReqToJSONTyped(json, false);
}

export function BoostReqToJSONTyped(
  value?: BoostReq | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amount: Int64ToJSON(value.amount),
    description: value.description,
    from: AddressToJSON(value.from),
    post: value.post,
    to: AddressToJSON(value.to),
  };
}
