/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Base64 } from "./Base64";

import { Base64FromJSON, Base64ToJSON } from "./Base64";

/**
 *
 * @export
 * @interface BoostResp
 */
export interface BoostResp {
  /**
   *
   * @type {Base64}
   * @memberof BoostResp
   */
  contract: Base64;
}

/**
 * Check if a given object implements the BoostResp interface.
 */
export function instanceOfBoostResp(value: object): value is BoostResp {
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  return true;
}

export function BoostRespFromJSON(json: any): BoostResp {
  return BoostRespFromJSONTyped(json, false);
}

export function BoostRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): BoostResp {
  if (json == null) {
    return json;
  }
  return {
    contract: Base64FromJSON(json.contract),
  };
}

export function BoostRespToJSON(json: any): BoostResp {
  return BoostRespToJSONTyped(json, false);
}

export function BoostRespToJSONTyped(
  value?: BoostResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: Base64ToJSON(value.contract),
  };
}
