/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Address } from "./Address";
import type { Int64 } from "./Int64";
import type { TimestampMillis } from "./TimestampMillis";

import { AddressFromJSON, AddressToJSON } from "./Address";
import { Int64FromJSON, Int64ToJSON } from "./Int64";
import {
  TimestampMillisFromJSON,
  TimestampMillisToJSON,
} from "./TimestampMillis";

/**
 *
 * @export
 * @interface Boost
 */
export interface Boost {
  /**
   *
   * @type {Int64}
   * @memberof Boost
   */
  amount: Int64;
  /**
   *
   * @type {string}
   * @memberof Boost
   */
  description?: string;
  /**
   *
   * @type {Address}
   * @memberof Boost
   */
  from: Address;
  /**
   *
   * @type {string}
   * @memberof Boost
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Boost
   */
  post?: string;
  /**
   *
   * @type {TimestampMillis}
   * @memberof Boost
   */
  timestamp: TimestampMillis;
  /**
   *
   * @type {Address}
   * @memberof Boost
   */
  to: Address;
}

/**
 * Check if a given object implements the Boost interface.
 */
export function instanceOfBoost(value: object): value is Boost {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("timestamp" in value) || value.timestamp === undefined) {
    return false;
  }
  if (!("from" in value) || value.from === undefined) {
    return false;
  }
  if (!("to" in value) || value.to === undefined) {
    return false;
  }
  if (!("amount" in value) || value.amount === undefined) {
    return false;
  }
  return true;
}

export function BoostFromJSON(json: any): Boost {
  return BoostFromJSONTyped(json, false);
}

export function BoostFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Boost {
  if (json == null) {
    return json;
  }
  return {
    amount: Int64FromJSON(json.amount),
    description: json.description == null ? undefined : json.description,
    from: AddressFromJSON(json.from),
    id: json.id,
    post: json.post == null ? undefined : json.post,
    timestamp: TimestampMillisFromJSON(json.timestamp),
    to: AddressFromJSON(json.to),
  };
}

export function BoostToJSON(json: any): Boost {
  return BoostToJSONTyped(json, false);
}

export function BoostToJSONTyped(
  value?: Boost | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amount: Int64ToJSON(value.amount),
    description: value.description,
    from: AddressToJSON(value.from),
    id: value.id,
    post: value.post,
    timestamp: TimestampMillisToJSON(value.timestamp),
    to: AddressToJSON(value.to),
  };
}
