/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Base64 } from "./Base64";

import { Base64FromJSON, Base64ToJSON } from "./Base64";

/**
 *
 * @export
 * @interface CreateOslfResp
 */
export interface CreateOslfResp {
  /**
   *
   * @type {Base64}
   * @memberof CreateOslfResp
   */
  contract: Base64;
  /**
   *
   * @type {string}
   * @memberof CreateOslfResp
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof CreateOslfResp
   */
  version: string;
}

/**
 * Check if a given object implements the CreateOslfResp interface.
 */
export function instanceOfCreateOslfResp(
  value: object,
): value is CreateOslfResp {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  return true;
}

export function CreateOslfRespFromJSON(json: any): CreateOslfResp {
  return CreateOslfRespFromJSONTyped(json, false);
}

export function CreateOslfRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateOslfResp {
  if (json == null) {
    return json;
  }
  return {
    contract: Base64FromJSON(json.contract),
    id: json.id,
    version: json.version,
  };
}

export function CreateOslfRespToJSON(json: any): CreateOslfResp {
  return CreateOslfRespToJSONTyped(json, false);
}

export function CreateOslfRespToJSONTyped(
  value?: CreateOslfResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: Base64ToJSON(value.contract),
    id: value.id,
    version: value.version,
  };
}
