/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface CreateOslfReq
 */
export interface CreateOslfReq {
  /**
   *
   * @type {string}
   * @memberof CreateOslfReq
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof CreateOslfReq
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof CreateOslfReq
   */
  query: string;
}

/**
 * Check if a given object implements the CreateOslfReq interface.
 */
export function instanceOfCreateOslfReq(value: object): value is CreateOslfReq {
  if (!("name" in value) || value.name === undefined) {
    return false;
  }
  if (!("query" in value) || value.query === undefined) {
    return false;
  }
  return true;
}

export function CreateOslfReqFromJSON(json: any): CreateOslfReq {
  return CreateOslfReqFromJSONTyped(json, false);
}

export function CreateOslfReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateOslfReq {
  if (json == null) {
    return json;
  }
  return {
    description: json.description == null ? undefined : json.description,
    name: json.name,
    query: json.query,
  };
}

export function CreateOslfReqToJSON(json: any): CreateOslfReq {
  return CreateOslfReqToJSONTyped(json, false);
}

export function CreateOslfReqToJSONTyped(
  value?: CreateOslfReq | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    description: value.description,
    name: value.name,
    query: value.query,
  };
}
