/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Base64 } from "./Base64";

import { Base64FromJSON, Base64ToJSON } from "./Base64";

/**
 *
 * @export
 * @interface DeleteOslfResp
 */
export interface DeleteOslfResp {
  /**
   *
   * @type {Base64}
   * @memberof DeleteOslfResp
   */
  contract: Base64;
}

/**
 * Check if a given object implements the DeleteOslfResp interface.
 */
export function instanceOfDeleteOslfResp(
  value: object,
): value is DeleteOslfResp {
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  return true;
}

export function DeleteOslfRespFromJSON(json: any): DeleteOslfResp {
  return DeleteOslfRespFromJSONTyped(json, false);
}

export function DeleteOslfRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeleteOslfResp {
  if (json == null) {
    return json;
  }
  return {
    contract: Base64FromJSON(json.contract),
  };
}

export function DeleteOslfRespToJSON(json: any): DeleteOslfResp {
  return DeleteOslfRespToJSONTyped(json, false);
}

export function DeleteOslfRespToJSONTyped(
  value?: DeleteOslfResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: Base64ToJSON(value.contract),
  };
}
