/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Base64 } from "./Base64";

import { Base64FromJSON, Base64ToJSON } from "./Base64";

/**
 *
 * @export
 * @interface DeleteAgentsTeamResp
 */
export interface DeleteAgentsTeamResp {
  /**
   *
   * @type {Base64}
   * @memberof DeleteAgentsTeamResp
   */
  contract: Base64;
}

/**
 * Check if a given object implements the DeleteAgentsTeamResp interface.
 */
export function instanceOfDeleteAgentsTeamResp(
  value: object,
): value is DeleteAgentsTeamResp {
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  return true;
}

export function DeleteAgentsTeamRespFromJSON(json: any): DeleteAgentsTeamResp {
  return DeleteAgentsTeamRespFromJSONTyped(json, false);
}

export function DeleteAgentsTeamRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeleteAgentsTeamResp {
  if (json == null) {
    return json;
  }
  return {
    contract: Base64FromJSON(json.contract),
  };
}

export function DeleteAgentsTeamRespToJSON(json: any): DeleteAgentsTeamResp {
  return DeleteAgentsTeamRespToJSONTyped(json, false);
}

export function DeleteAgentsTeamRespToJSONTyped(
  value?: DeleteAgentsTeamResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: Base64ToJSON(value.contract),
  };
}
