/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Base64 } from "./Base64";

import { Base64FromJSON, Base64ToJSON } from "./Base64";

/**
 *
 * @export
 * @interface DeleteAgentResp
 */
export interface DeleteAgentResp {
  /**
   *
   * @type {Base64}
   * @memberof DeleteAgentResp
   */
  contract: Base64;
}

/**
 * Check if a given object implements the DeleteAgentResp interface.
 */
export function instanceOfDeleteAgentResp(
  value: object,
): value is DeleteAgentResp {
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  return true;
}

export function DeleteAgentRespFromJSON(json: any): DeleteAgentResp {
  return DeleteAgentRespFromJSONTyped(json, false);
}

export function DeleteAgentRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeleteAgentResp {
  if (json == null) {
    return json;
  }
  return {
    contract: Base64FromJSON(json.contract),
  };
}

export function DeleteAgentRespToJSON(json: any): DeleteAgentResp {
  return DeleteAgentRespToJSONTyped(json, false);
}

export function DeleteAgentRespToJSONTyped(
  value?: DeleteAgentResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: Base64ToJSON(value.contract),
  };
}
