/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Base64 } from "./Base64";

import { Base64FromJSON, Base64ToJSON } from "./Base64";

/**
 *
 * @export
 * @interface DeployAgentsTeamResp
 */
export interface DeployAgentsTeamResp {
  /**
   *
   * @type {Base64}
   * @memberof DeployAgentsTeamResp
   */
  contract: Base64;
  /**
   *
   * @type {string}
   * @memberof DeployAgentsTeamResp
   */
  name: string;
}

/**
 * Check if a given object implements the DeployAgentsTeamResp interface.
 */
export function instanceOfDeployAgentsTeamResp(
  value: object,
): value is DeployAgentsTeamResp {
  if (!("name" in value) || value.name === undefined) {
    return false;
  }
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  return true;
}

export function DeployAgentsTeamRespFromJSON(json: any): DeployAgentsTeamResp {
  return DeployAgentsTeamRespFromJSONTyped(json, false);
}

export function DeployAgentsTeamRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeployAgentsTeamResp {
  if (json == null) {
    return json;
  }
  return {
    contract: Base64FromJSON(json.contract),
    name: json.name,
  };
}

export function DeployAgentsTeamRespToJSON(json: any): DeployAgentsTeamResp {
  return DeployAgentsTeamRespToJSONTyped(json, false);
}

export function DeployAgentsTeamRespToJSONTyped(
  value?: DeployAgentsTeamResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: Base64ToJSON(value.contract),
    name: value.name,
  };
}
