/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SignedContract } from "./SignedContract";

import { SignedContractFromJSON, SignedContractToJSON } from "./SignedContract";

/**
 *
 * @export
 * @interface DeploySignedAgentsTeamReq
 */
export interface DeploySignedAgentsTeamReq {
  /**
   *
   * @type {SignedContract}
   * @memberof DeploySignedAgentsTeamReq
   */
  contract: SignedContract;
  /**
   *
   * @type {SignedContract}
   * @memberof DeploySignedAgentsTeamReq
   */
  system?: SignedContract;
}

/**
 * Check if a given object implements the DeploySignedAgentsTeamReq interface.
 */
export function instanceOfDeploySignedAgentsTeamReq(
  value: object,
): value is DeploySignedAgentsTeamReq {
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  return true;
}

export function DeploySignedAgentsTeamReqFromJSON(
  json: any,
): DeploySignedAgentsTeamReq {
  return DeploySignedAgentsTeamReqFromJSONTyped(json, false);
}

export function DeploySignedAgentsTeamReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeploySignedAgentsTeamReq {
  if (json == null) {
    return json;
  }
  return {
    contract: SignedContractFromJSON(json.contract),
    system:
      json.system == null ? undefined : SignedContractFromJSON(json.system),
  };
}

export function DeploySignedAgentsTeamReqToJSON(
  json: any,
): DeploySignedAgentsTeamReq {
  return DeploySignedAgentsTeamReqToJSONTyped(json, false);
}

export function DeploySignedAgentsTeamReqToJSONTyped(
  value?: DeploySignedAgentsTeamReq | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: SignedContractToJSON(value.contract),
    system: SignedContractToJSON(value.system),
  };
}
