/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Address } from "./Address";
import type { Int64 } from "./Int64";
import type { RegistryDeploy } from "./RegistryDeploy";

import { AddressFromJSON, AddressToJSON } from "./Address";
import { Int64FromJSON, Int64ToJSON } from "./Int64";
import { RegistryDeployFromJSON, RegistryDeployToJSON } from "./RegistryDeploy";

/**
 *
 * @export
 * @interface DeployAgentsTeamReqDeployAgentsTeam
 */
export interface DeployAgentsTeamReqDeployAgentsTeam {
  /**
   *
   * @type {Address}
   * @memberof DeployAgentsTeamReqDeployAgentsTeam
   */
  address: Address;
  /**
   *
   * @type {RegistryDeploy}
   * @memberof DeployAgentsTeamReqDeployAgentsTeam
   */
  deploy: RegistryDeploy;
  /**
   *
   * @type {string}
   * @memberof DeployAgentsTeamReqDeployAgentsTeam
   */
  id: string;
  /**
   *
   * @type {Int64}
   * @memberof DeployAgentsTeamReqDeployAgentsTeam
   */
  phloLimit: Int64;
  /**
   *
   * @type {string}
   * @memberof DeployAgentsTeamReqDeployAgentsTeam
   */
  type: DeployAgentsTeamReqDeployAgentsTeamTypeEnum;
  /**
   *
   * @type {string}
   * @memberof DeployAgentsTeamReqDeployAgentsTeam
   */
  version: string;
}

/**
 * @export
 */
export const DeployAgentsTeamReqDeployAgentsTeamTypeEnum = {
  AgentsTeam: "AgentsTeam",
} as const;
export type DeployAgentsTeamReqDeployAgentsTeamTypeEnum =
  (typeof DeployAgentsTeamReqDeployAgentsTeamTypeEnum)[keyof typeof DeployAgentsTeamReqDeployAgentsTeamTypeEnum];

/**
 * Check if a given object implements the DeployAgentsTeamReqDeployAgentsTeam interface.
 */
export function instanceOfDeployAgentsTeamReqDeployAgentsTeam(
  value: object,
): value is DeployAgentsTeamReqDeployAgentsTeam {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("address" in value) || value.address === undefined) {
    return false;
  }
  if (!("phloLimit" in value) || value.phloLimit === undefined) {
    return false;
  }
  if (!("deploy" in value) || value.deploy === undefined) {
    return false;
  }
  if (!("type" in value) || value.type === undefined) {
    return false;
  }
  return true;
}

export function DeployAgentsTeamReqDeployAgentsTeamFromJSON(
  json: any,
): DeployAgentsTeamReqDeployAgentsTeam {
  return DeployAgentsTeamReqDeployAgentsTeamFromJSONTyped(json, false);
}

export function DeployAgentsTeamReqDeployAgentsTeamFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeployAgentsTeamReqDeployAgentsTeam {
  if (json == null) {
    return json;
  }
  return {
    address: AddressFromJSON(json.address),
    deploy: RegistryDeployFromJSON(json.deploy),
    id: json.id,
    phloLimit: Int64FromJSON(json.phlo_limit),
    type: json.type,
    version: json.version,
  };
}

export function DeployAgentsTeamReqDeployAgentsTeamToJSON(
  json: any,
): DeployAgentsTeamReqDeployAgentsTeam {
  return DeployAgentsTeamReqDeployAgentsTeamToJSONTyped(json, false);
}

export function DeployAgentsTeamReqDeployAgentsTeamToJSONTyped(
  value?: DeployAgentsTeamReqDeployAgentsTeam | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    address: AddressToJSON(value.address),
    deploy: RegistryDeployToJSON(value.deploy),
    id: value.id,
    phlo_limit: Int64ToJSON(value.phloLimit),
    type: value.type,
    version: value.version,
  };
}
