/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Int64 } from "./Int64";

import { Int64FromJSON, Int64ToJSON } from "./Int64";

/**
 *
 * @export
 * @interface DeployAgentsTeam
 */
export interface DeployAgentsTeam {
  /**
   *
   * @type {string}
   * @memberof DeployAgentsTeam
   */
  address: string;
  /**
   *
   * @type {string}
   * @memberof DeployAgentsTeam
   */
  id: string;
  /**
   *
   * @type {Int64}
   * @memberof DeployAgentsTeam
   */
  phloLimit: Int64;
  /**
   *
   * @type {string}
   * @memberof DeployAgentsTeam
   */
  version: string;
}

/**
 * Check if a given object implements the DeployAgentsTeam interface.
 */
export function instanceOfDeployAgentsTeam(
  value: object,
): value is DeployAgentsTeam {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("address" in value) || value.address === undefined) {
    return false;
  }
  if (!("phloLimit" in value) || value.phloLimit === undefined) {
    return false;
  }
  return true;
}

export function DeployAgentsTeamFromJSON(json: any): DeployAgentsTeam {
  return DeployAgentsTeamFromJSONTyped(json, false);
}

export function DeployAgentsTeamFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeployAgentsTeam {
  if (json == null) {
    return json;
  }
  return {
    address: json.address,
    id: json.id,
    phloLimit: Int64FromJSON(json.phlo_limit),
    version: json.version,
  };
}

export function DeployAgentsTeamToJSON(json: any): DeployAgentsTeam {
  return DeployAgentsTeamToJSONTyped(json, false);
}

export function DeployAgentsTeamToJSONTyped(
  value?: DeployAgentsTeam | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    address: value.address,
    id: value.id,
    phlo_limit: Int64ToJSON(value.phloLimit),
    version: value.version,
  };
}
