/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FireskyReply } from "./FireskyReply";
import type { SignedContract } from "./SignedContract";

import { FireskyReplyFromJSON, FireskyReplyToJSON } from "./FireskyReply";
import { SignedContractFromJSON, SignedContractToJSON } from "./SignedContract";

/**
 *
 * @export
 * @interface DeploySignedRunAgentsTeamFireskyReq
 */
export interface DeploySignedRunAgentsTeamFireskyReq {
  /**
   *
   * @type {SignedContract}
   * @memberof DeploySignedRunAgentsTeamFireskyReq
   */
  contract: SignedContract;
  /**
   *
   * @type {FireskyReply}
   * @memberof DeploySignedRunAgentsTeamFireskyReq
   */
  replyTo?: FireskyReply;
}

/**
 * Check if a given object implements the DeploySignedRunAgentsTeamFireskyReq interface.
 */
export function instanceOfDeploySignedRunAgentsTeamFireskyReq(
  value: object,
): value is DeploySignedRunAgentsTeamFireskyReq {
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  return true;
}

export function DeploySignedRunAgentsTeamFireskyReqFromJSON(
  json: any,
): DeploySignedRunAgentsTeamFireskyReq {
  return DeploySignedRunAgentsTeamFireskyReqFromJSONTyped(json, false);
}

export function DeploySignedRunAgentsTeamFireskyReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeploySignedRunAgentsTeamFireskyReq {
  if (json == null) {
    return json;
  }
  return {
    contract: SignedContractFromJSON(json.contract),
    replyTo:
      json.reply_to == null ? undefined : FireskyReplyFromJSON(json.reply_to),
  };
}

export function DeploySignedRunAgentsTeamFireskyReqToJSON(
  json: any,
): DeploySignedRunAgentsTeamFireskyReq {
  return DeploySignedRunAgentsTeamFireskyReqToJSONTyped(json, false);
}

export function DeploySignedRunAgentsTeamFireskyReqToJSONTyped(
  value?: DeploySignedRunAgentsTeamFireskyReq | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: SignedContractToJSON(value.contract),
    reply_to: FireskyReplyToJSON(value.replyTo),
  };
}
