/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Log } from "./Log";

import { LogFromJSON, LogToJSON } from "./Log";

/**
 *
 * @export
 * @interface DeploySignedTestRespSignedTestDeplotLogs
 */
export interface DeploySignedTestRespSignedTestDeplotLogs {
  /**
   *
   * @type {Array<Log>}
   * @memberof DeploySignedTestRespSignedTestDeplotLogs
   */
  logs: Array<Log>;
  /**
   *
   * @type {string}
   * @memberof DeploySignedTestRespSignedTestDeplotLogs
   */
  type: DeploySignedTestRespSignedTestDeplotLogsTypeEnum;
}

/**
 * @export
 */
export const DeploySignedTestRespSignedTestDeplotLogsTypeEnum = {
  Ok: "Ok",
} as const;
export type DeploySignedTestRespSignedTestDeplotLogsTypeEnum =
  (typeof DeploySignedTestRespSignedTestDeplotLogsTypeEnum)[keyof typeof DeploySignedTestRespSignedTestDeplotLogsTypeEnum];

/**
 * Check if a given object implements the DeploySignedTestRespSignedTestDeplotLogs interface.
 */
export function instanceOfDeploySignedTestRespSignedTestDeplotLogs(
  value: object,
): value is DeploySignedTestRespSignedTestDeplotLogs {
  if (!("logs" in value) || value.logs === undefined) {
    return false;
  }
  if (!("type" in value) || value.type === undefined) {
    return false;
  }
  return true;
}

export function DeploySignedTestRespSignedTestDeplotLogsFromJSON(
  json: any,
): DeploySignedTestRespSignedTestDeplotLogs {
  return DeploySignedTestRespSignedTestDeplotLogsFromJSONTyped(json, false);
}

export function DeploySignedTestRespSignedTestDeplotLogsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeploySignedTestRespSignedTestDeplotLogs {
  if (json == null) {
    return json;
  }
  return {
    logs: (json.logs as Array<any>).map(LogFromJSON),
    type: json.type,
  };
}

export function DeploySignedTestRespSignedTestDeplotLogsToJSON(
  json: any,
): DeploySignedTestRespSignedTestDeplotLogs {
  return DeploySignedTestRespSignedTestDeplotLogsToJSONTyped(json, false);
}

export function DeploySignedTestRespSignedTestDeplotLogsToJSONTyped(
  value?: DeploySignedTestRespSignedTestDeplotLogs | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    logs: (value.logs as Array<any>).map(LogToJSON),
    type: value.type,
  };
}
