/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DeploySignedTestRespTestDeployFailed
 */
export interface DeploySignedTestRespTestDeployFailed {
  /**
   *
   * @type {string}
   * @memberof DeploySignedTestRespTestDeployFailed
   */
  error: string;
  /**
   *
   * @type {DeploySignedTestRespTestDeployFailedTypeEnum}
   * @memberof DeploySignedTestRespTestDeployFailed
   */
  type: DeploySignedTestRespTestDeployFailedTypeEnum;
}

/**
 * @export
 */
export const DeploySignedTestRespTestDeployFailedTypeEnum = {
  TestDeployFailed: "TestDeployFailed",
} as const;
export type DeploySignedTestRespTestDeployFailedTypeEnum =
  (typeof DeploySignedTestRespTestDeployFailedTypeEnum)[keyof typeof DeploySignedTestRespTestDeployFailedTypeEnum];

/**
 * Check if a given object implements the DeploySignedTestRespTestDeployFailed interface.
 */
export function instanceOfDeploySignedTestRespTestDeployFailed(
  value: object,
): value is DeploySignedTestRespTestDeployFailed {
  if (!("error" in value) || value.error === undefined) {
    return false;
  }
  if (!("type" in value) || value.type === undefined) {
    return false;
  }
  return true;
}

export function DeploySignedTestRespTestDeployFailedFromJSON(
  json: any,
): DeploySignedTestRespTestDeployFailed {
  return DeploySignedTestRespTestDeployFailedFromJSONTyped(json, false);
}

export function DeploySignedTestRespTestDeployFailedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeploySignedTestRespTestDeployFailed {
  if (json == null) {
    return json;
  }
  return {
    error: json.error,
    type: json.type,
  };
}

export function DeploySignedTestRespTestDeployFailedToJSON(
  json: any,
): DeploySignedTestRespTestDeployFailed {
  return DeploySignedTestRespTestDeployFailedToJSONTyped(json, false);
}

export function DeploySignedTestRespTestDeployFailedToJSONTyped(
  value?: DeploySignedTestRespTestDeployFailed | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    error: value.error,
    type: value.type,
  };
}
