/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Address } from "./Address";
import type { Int64 } from "./Int64";
import type { RegistryDeploy } from "./RegistryDeploy";

import { AddressFromJSON, AddressToJSON } from "./Address";
import { Int64FromJSON, Int64ToJSON } from "./Int64";
import { RegistryDeployFromJSON, RegistryDeployToJSON } from "./RegistryDeploy";

/**
 *
 * @export
 * @interface DeployAgentsTeam
 */
export interface DeployAgentsTeam {
  /**
   *
   * @type {Address}
   * @memberof DeployAgentsTeam
   */
  address: Address;
  /**
   *
   * @type {RegistryDeploy}
   * @memberof DeployAgentsTeam
   */
  deploy: RegistryDeploy;
  /**
   *
   * @type {string}
   * @memberof DeployAgentsTeam
   */
  id: string;
  /**
   *
   * @type {Int64}
   * @memberof DeployAgentsTeam
   */
  phloLimit: Int64;
  /**
   *
   * @type {string}
   * @memberof DeployAgentsTeam
   */
  version: string;
}

/**
 * Check if a given object implements the DeployAgentsTeam interface.
 */
export function instanceOfDeployAgentsTeam(
  value: object,
): value is DeployAgentsTeam {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("address" in value) || value.address === undefined) {
    return false;
  }
  if (!("phloLimit" in value) || value.phloLimit === undefined) {
    return false;
  }
  if (!("deploy" in value) || value.deploy === undefined) {
    return false;
  }
  return true;
}

export function DeployAgentsTeamFromJSON(json: any): DeployAgentsTeam {
  return DeployAgentsTeamFromJSONTyped(json, false);
}

export function DeployAgentsTeamFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeployAgentsTeam {
  if (json == null) {
    return json;
  }
  return {
    address: AddressFromJSON(json.address),
    deploy: RegistryDeployFromJSON(json.deploy),
    id: json.id,
    phloLimit: Int64FromJSON(json.phlo_limit),
    version: json.version,
  };
}

export function DeployAgentsTeamToJSON(json: any): DeployAgentsTeam {
  return DeployAgentsTeamToJSONTyped(json, false);
}

export function DeployAgentsTeamToJSONTyped(
  value?: DeployAgentsTeam | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    address: AddressToJSON(value.address),
    deploy: RegistryDeployToJSON(value.deploy),
    id: value.id,
    phlo_limit: Int64ToJSON(value.phloLimit),
    version: value.version,
  };
}
