/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Int64 } from "./Int64";

import { Int64FromJSON, Int64ToJSON } from "./Int64";

/**
 *
 * @export
 * @interface DeployAgentsTeamReqDeployGraph
 */
export interface DeployAgentsTeamReqDeployGraph {
  /**
   *
   * @type {string}
   * @memberof DeployAgentsTeamReqDeployGraph
   */
  graph: string;
  /**
   *
   * @type {Int64}
   * @memberof DeployAgentsTeamReqDeployGraph
   */
  phloLimit: Int64;
  /**
   *
   * @type {string}
   * @memberof DeployAgentsTeamReqDeployGraph
   */
  type: DeployAgentsTeamReqDeployGraphTypeEnum;
}

/**
 * @export
 */
export const DeployAgentsTeamReqDeployGraphTypeEnum = {
  Graph: "Graph",
} as const;
export type DeployAgentsTeamReqDeployGraphTypeEnum =
  (typeof DeployAgentsTeamReqDeployGraphTypeEnum)[keyof typeof DeployAgentsTeamReqDeployGraphTypeEnum];

/**
 * Check if a given object implements the DeployAgentsTeamReqDeployGraph interface.
 */
export function instanceOfDeployAgentsTeamReqDeployGraph(
  value: object,
): value is DeployAgentsTeamReqDeployGraph {
  if (!("graph" in value) || value.graph === undefined) {
    return false;
  }
  if (!("phloLimit" in value) || value.phloLimit === undefined) {
    return false;
  }
  if (!("type" in value) || value.type === undefined) {
    return false;
  }
  return true;
}

export function DeployAgentsTeamReqDeployGraphFromJSON(
  json: any,
): DeployAgentsTeamReqDeployGraph {
  return DeployAgentsTeamReqDeployGraphFromJSONTyped(json, false);
}

export function DeployAgentsTeamReqDeployGraphFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeployAgentsTeamReqDeployGraph {
  if (json == null) {
    return json;
  }
  return {
    graph: json.graph,
    phloLimit: Int64FromJSON(json.phlo_limit),
    type: json.type,
  };
}

export function DeployAgentsTeamReqDeployGraphToJSON(
  json: any,
): DeployAgentsTeamReqDeployGraph {
  return DeployAgentsTeamReqDeployGraphToJSONTyped(json, false);
}

export function DeployAgentsTeamReqDeployGraphToJSONTyped(
  value?: DeployAgentsTeamReqDeployGraph | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    graph: value.graph,
    phlo_limit: Int64ToJSON(value.phloLimit),
    type: value.type,
  };
}
