/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface DeployDemoReq
 */
export interface DeployDemoReq {
  /**
   *
   * @type {string}
   * @memberof DeployDemoReq
   */
  name: string;
}

/**
 * Check if a given object implements the DeployDemoReq interface.
 */
export function instanceOfDeployDemoReq(value: object): value is DeployDemoReq {
  if (!("name" in value) || value.name === undefined) {
    return false;
  }
  return true;
}

export function DeployDemoReqFromJSON(json: any): DeployDemoReq {
  return DeployDemoReqFromJSONTyped(json, false);
}

export function DeployDemoReqFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): DeployDemoReq {
  if (json == null) {
    return json;
  }
  return {
    name: json.name,
  };
}

export function DeployDemoReqToJSON(json: any): DeployDemoReq {
  return DeployDemoReqToJSONTyped(json, false);
}

export function DeployDemoReqToJSONTyped(
  value?: DeployDemoReq | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: value.name,
  };
}
