/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface EnvDeployFailed
 */
export interface EnvDeployFailed {
  /**
   *
   * @type {string}
   * @memberof EnvDeployFailed
   */
  error: string;
}

/**
 * Check if a given object implements the EnvDeployFailed interface.
 */
export function instanceOfEnvDeployFailed(
  value: object,
): value is EnvDeployFailed {
  if (!("error" in value) || value.error === undefined) {
    return false;
  }
  return true;
}

export function EnvDeployFailedFromJSON(json: any): EnvDeployFailed {
  return EnvDeployFailedFromJSONTyped(json, false);
}

export function EnvDeployFailedFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): EnvDeployFailed {
  if (json == null) {
    return json;
  }
  return {
    error: json.error,
  };
}

export function EnvDeployFailedToJSON(json: any): EnvDeployFailed {
  return EnvDeployFailedToJSONTyped(json, false);
}

export function EnvDeployFailedToJSONTyped(
  value?: EnvDeployFailed | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    error: value.error,
  };
}
