/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Binding } from "./Binding";

import { BindingFromJSON, BindingToJSON } from "./Binding";

/**
 *
 * @export
 * @interface GEdgeAnon
 */
export interface GEdgeAnon {
  /**
   *
   * @type {Binding}
   * @memberof GEdgeAnon
   */
  binding1: Binding;
  /**
   *
   * @type {Binding}
   * @memberof GEdgeAnon
   */
  binding2: Binding;
}

/**
 * Check if a given object implements the GEdgeAnon interface.
 */
export function instanceOfGEdgeAnon(value: object): value is GEdgeAnon {
  if (!("binding1" in value) || value.binding1 === undefined) {
    return false;
  }
  if (!("binding2" in value) || value.binding2 === undefined) {
    return false;
  }
  return true;
}

export function GEdgeAnonFromJSON(json: any): GEdgeAnon {
  return GEdgeAnonFromJSONTyped(json, false);
}

export function GEdgeAnonFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GEdgeAnon {
  if (json == null) {
    return json;
  }
  return {
    binding1: BindingFromJSON(json.binding_1),
    binding2: BindingFromJSON(json.binding_2),
  };
}

export function GEdgeAnonToJSON(json: any): GEdgeAnon {
  return GEdgeAnonToJSONTyped(json, false);
}

export function GEdgeAnonToJSONTyped(
  value?: GEdgeAnon | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    binding_1: BindingToJSON(value.binding1),
    binding_2: BindingToJSON(value.binding2),
  };
}
