/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Graph } from "./Graph";
import { GraphFromJSON, GraphToJSON } from "./Graph";
import type { Vertex } from "./Vertex";
import { VertexFromJSON, VertexToJSON } from "./Vertex";

/**
 *
 * @export
 * @interface GraphGVertex
 */
export interface GraphGVertex {
  /**
   *
   * @type {Graph}
   * @memberof GraphGVertex
   */
  graph: Graph;
  /**
   *
   * @type {string}
   * @memberof GraphGVertex
   */
  type: GraphGVertexTypeEnum;
  /**
   *
   * @type {Vertex}
   * @memberof GraphGVertex
   */
  vertex: Vertex;
}

/**
 * @export
 */
export const GraphGVertexTypeEnum = {
  Vertex: "Vertex",
} as const;
export type GraphGVertexTypeEnum = (typeof GraphGVertexTypeEnum)[keyof typeof GraphGVertexTypeEnum];

/**
 * Check if a given object implements the GraphGVertex interface.
 */
export function instanceOfGraphGVertex(value: object): value is GraphGVertex {
  if (!("graph" in value) || value.graph === undefined) {
    return false;
  }
  if (!("vertex" in value) || value.vertex === undefined) {
    return false;
  }
  if (!("type" in value) || value.type === undefined) {
    return false;
  }
  return true;
}

export function GraphGVertexFromJSON(json: any): GraphGVertex {
  return GraphGVertexFromJSONTyped(json, false);
}

export function GraphGVertexFromJSONTyped(json: any, ignoreDiscriminator: boolean): GraphGVertex {
  if (json == null) {
    return json;
  }
  return {
    graph: GraphFromJSON(json.graph),
    type: json.type,
    vertex: VertexFromJSON(json.vertex),
  };
}

export function GraphGVertexToJSON(json: any): GraphGVertex {
  return GraphGVertexToJSONTyped(json, false);
}

export function GraphGVertexToJSONTyped(
  value?: GraphGVertex | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    graph: GraphToJSON(value.graph),
    type: value.type,
    vertex: VertexToJSON(value.vertex),
  };
}
