/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Graph } from "./Graph";

import { GraphFromJSON, GraphToJSON } from "./Graph";

/**
 *
 * @export
 * @interface GraphGTensor
 */
export interface GraphGTensor {
  /**
   *
   * @type {Graph}
   * @memberof GraphGTensor
   */
  graph1: Graph;
  /**
   *
   * @type {Graph}
   * @memberof GraphGTensor
   */
  graph2: Graph;
  /**
   *
   * @type {string}
   * @memberof GraphGTensor
   */
  type: GraphGTensorTypeEnum;
}

/**
 * @export
 */
export const GraphGTensorTypeEnum = {
  Tensor: "Tensor",
} as const;
export type GraphGTensorTypeEnum =
  (typeof GraphGTensorTypeEnum)[keyof typeof GraphGTensorTypeEnum];

/**
 * Check if a given object implements the GraphGTensor interface.
 */
export function instanceOfGraphGTensor(value: object): value is GraphGTensor {
  if (!("graph1" in value) || value.graph1 === undefined) {
    return false;
  }
  if (!("graph2" in value) || value.graph2 === undefined) {
    return false;
  }
  if (!("type" in value) || value.type === undefined) {
    return false;
  }
  return true;
}

export function GraphGTensorFromJSON(json: any): GraphGTensor {
  return GraphGTensorFromJSONTyped(json, false);
}

export function GraphGTensorFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GraphGTensor {
  if (json == null) {
    return json;
  }
  return {
    graph1: GraphFromJSON(json.graph_1),
    graph2: GraphFromJSON(json.graph_2),
    type: json.type,
  };
}

export function GraphGTensorToJSON(json: any): GraphGTensor {
  return GraphGTensorToJSONTyped(json, false);
}

export function GraphGTensorToJSONTyped(
  value?: GraphGTensor | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    graph_1: GraphToJSON(value.graph1),
    graph_2: GraphToJSON(value.graph2),
    type: value.type,
  };
}
