/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Binding } from "./Binding";
import { BindingFromJSON, BindingToJSON } from "./Binding";
import type { Name } from "./Name";
import { NameFromJSON, NameToJSON } from "./Name";

/**
 *
 * @export
 * @interface GraphGEdgeNamed
 */
export interface GraphGEdgeNamed {
  /**
   *
   * @type {Binding}
   * @memberof GraphGEdgeNamed
   */
  binding1: Binding;
  /**
   *
   * @type {Binding}
   * @memberof GraphGEdgeNamed
   */
  binding2: Binding;
  /**
   *
   * @type {Name}
   * @memberof GraphGEdgeNamed
   */
  name: Name;
  /**
   *
   * @type {string}
   * @memberof GraphGEdgeNamed
   */
  type: GraphGEdgeNamedTypeEnum;
}

/**
 * @export
 */
export const GraphGEdgeNamedTypeEnum = {
  EdgeNamed: "EdgeNamed",
} as const;
export type GraphGEdgeNamedTypeEnum =
  (typeof GraphGEdgeNamedTypeEnum)[keyof typeof GraphGEdgeNamedTypeEnum];

/**
 * Check if a given object implements the GraphGEdgeNamed interface.
 */
export function instanceOfGraphGEdgeNamed(value: object): value is GraphGEdgeNamed {
  if (!("binding1" in value) || value.binding1 === undefined) {
    return false;
  }
  if (!("binding2" in value) || value.binding2 === undefined) {
    return false;
  }
  if (!("name" in value) || value.name === undefined) {
    return false;
  }
  if (!("type" in value) || value.type === undefined) {
    return false;
  }
  return true;
}

export function GraphGEdgeNamedFromJSON(json: any): GraphGEdgeNamed {
  return GraphGEdgeNamedFromJSONTyped(json, false);
}

export function GraphGEdgeNamedFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): GraphGEdgeNamed {
  if (json == null) {
    return json;
  }
  return {
    binding1: BindingFromJSON(json.binding_1),
    binding2: BindingFromJSON(json.binding_2),
    name: NameFromJSON(json.name),
    type: json.type,
  };
}

export function GraphGEdgeNamedToJSON(json: any): GraphGEdgeNamed {
  return GraphGEdgeNamedToJSONTyped(json, false);
}

export function GraphGEdgeNamedToJSONTyped(
  value?: GraphGEdgeNamed | null,
  _ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    binding_1: BindingToJSON(value.binding1),
    binding_2: BindingToJSON(value.binding2),
    name: NameToJSON(value.name),
    type: value.type,
  };
}
