/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Graph } from "./Graph";

import { GraphFromJSON, GraphToJSON } from "./Graph";

/**
 *
 * @export
 * @interface GraphGSubgraph
 */
export interface GraphGSubgraph {
  /**
   *
   * @type {string}
   * @memberof GraphGSubgraph
   */
  _var: string;
  /**
   *
   * @type {Graph}
   * @memberof GraphGSubgraph
   */
  graph1: Graph;
  /**
   *
   * @type {Graph}
   * @memberof GraphGSubgraph
   */
  graph2: Graph;
  /**
   *
   * @type {string}
   * @memberof GraphGSubgraph
   */
  type: GraphGSubgraphTypeEnum;
}

/**
 * @export
 */
export const GraphGSubgraphTypeEnum = {
  Subgraph: "Subgraph",
} as const;
export type GraphGSubgraphTypeEnum =
  (typeof GraphGSubgraphTypeEnum)[keyof typeof GraphGSubgraphTypeEnum];

/**
 * Check if a given object implements the GraphGSubgraph interface.
 */
export function instanceOfGraphGSubgraph(value: object): value is GraphGSubgraph {
  if (!("graph1" in value) || value.graph1 === undefined) {
    return false;
  }
  if (!("graph2" in value) || value.graph2 === undefined) {
    return false;
  }
  if (!("_var" in value) || value._var === undefined) {
    return false;
  }
  if (!("type" in value) || value.type === undefined) {
    return false;
  }
  return true;
}

export function GraphGSubgraphFromJSON(json: any): GraphGSubgraph {
  return GraphGSubgraphFromJSONTyped(json, false);
}

export function GraphGSubgraphFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): GraphGSubgraph {
  if (json == null) {
    return json;
  }
  return {
    _var: json.var,
    graph1: GraphFromJSON(json.graph_1),
    graph2: GraphFromJSON(json.graph_2),
    type: json.type,
  };
}

export function GraphGSubgraphToJSON(json: any): GraphGSubgraph {
  return GraphGSubgraphToJSONTyped(json, false);
}

export function GraphGSubgraphToJSONTyped(
  value?: GraphGSubgraph | null,
  _ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    graph_1: GraphToJSON(value.graph1),
    graph_2: GraphToJSON(value.graph2),
    type: value.type,
    var: value._var,
  };
}
