/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Graph } from "./Graph";

import { GraphFromJSON, GraphToJSON } from "./Graph";

/**
 *
 * @export
 * @interface GRuleAnon
 */
export interface GRuleAnon {
  /**
   *
   * @type {Graph}
   * @memberof GRuleAnon
   */
  graph1: Graph;
  /**
   *
   * @type {Graph}
   * @memberof GRuleAnon
   */
  graph2: Graph;
}

/**
 * Check if a given object implements the GRuleAnon interface.
 */
export function instanceOfGRuleAnon(value: object): value is GRuleAnon {
  if (!("graph1" in value) || value.graph1 === undefined) {
    return false;
  }
  if (!("graph2" in value) || value.graph2 === undefined) {
    return false;
  }
  return true;
}

export function GRuleAnonFromJSON(json: any): GRuleAnon {
  return GRuleAnonFromJSONTyped(json, false);
}

export function GRuleAnonFromJSONTyped(json: any, _ignoreDiscriminator: boolean): GRuleAnon {
  if (json == null) {
    return json;
  }
  return {
    graph1: GraphFromJSON(json.graph_1),
    graph2: GraphFromJSON(json.graph_2),
  };
}

export function GRuleAnonToJSON(json: any): GRuleAnon {
  return GRuleAnonToJSONTyped(json, false);
}

export function GRuleAnonToJSONTyped(
  value?: GRuleAnon | null,
  _ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    graph_1: GraphToJSON(value.graph1),
    graph_2: GraphToJSON(value.graph2),
  };
}
