/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Graph } from "./Graph";

import { GraphFromJSON, GraphToJSON } from "./Graph";

/**
 *
 * @export
 * @interface GSubgraph
 */
export interface GSubgraph {
  /**
   *
   * @type {string}
   * @memberof GSubgraph
   */
  _var: string;
  /**
   *
   * @type {Graph}
   * @memberof GSubgraph
   */
  graph1: Graph;
  /**
   *
   * @type {Graph}
   * @memberof GSubgraph
   */
  graph2: Graph;
}

/**
 * Check if a given object implements the GSubgraph interface.
 */
export function instanceOfGSubgraph(value: object): value is GSubgraph {
  if (!("graph1" in value) || value.graph1 === undefined) {
    return false;
  }
  if (!("graph2" in value) || value.graph2 === undefined) {
    return false;
  }
  if (!("_var" in value) || value._var === undefined) {
    return false;
  }
  return true;
}

export function GSubgraphFromJSON(json: any): GSubgraph {
  return GSubgraphFromJSONTyped(json, false);
}

export function GSubgraphFromJSONTyped(json: any, _ignoreDiscriminator: boolean): GSubgraph {
  if (json == null) {
    return json;
  }
  return {
    _var: json.var,
    graph1: GraphFromJSON(json.graph_1),
    graph2: GraphFromJSON(json.graph_2),
  };
}

export function GSubgraphToJSON(json: any): GSubgraph {
  return GSubgraphToJSONTyped(json, false);
}

export function GSubgraphToJSONTyped(
  value?: GSubgraph | null,
  _ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    graph_1: GraphToJSON(value.graph1),
    graph_2: GraphToJSON(value.graph2),
    var: value._var,
  };
}
