/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Graph } from "./Graph";

import { GraphFromJSON, GraphToJSON } from "./Graph";

/**
 *
 * @export
 * @interface GVar
 */
export interface GVar {
  /**
   *
   * @type {string}
   * @memberof GVar
   */
  _var: string;
  /**
   *
   * @type {Graph}
   * @memberof GVar
   */
  graph: Graph;
}

/**
 * Check if a given object implements the GVar interface.
 */
export function instanceOfGVar(value: object): value is GVar {
  if (!("graph" in value) || value.graph === undefined) {
    return false;
  }
  if (!("_var" in value) || value._var === undefined) {
    return false;
  }
  return true;
}

export function GVarFromJSON(json: any): GVar {
  return GVarFromJSONTyped(json, false);
}

export function GVarFromJSONTyped(json: any, ignoreDiscriminator: boolean): GVar {
  if (json == null) {
    return json;
  }
  return {
    _var: json.var,
    graph: GraphFromJSON(json.graph),
  };
}

export function GVarToJSON(json: any): GVar {
  return GVarToJSONTyped(json, false);
}

export function GVarToJSONTyped(value?: GVar | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    graph: GraphToJSON(value.graph),
    var: value._var,
  };
}
