/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Graph } from "./Graph";
import type { Vertex } from "./Vertex";

import { GraphFromJSON, GraphToJSON } from "./Graph";
import { VertexFromJSON, VertexToJSON } from "./Vertex";

/**
 *
 * @export
 * @interface GVertex
 */
export interface GVertex {
  /**
   *
   * @type {Graph}
   * @memberof GVertex
   */
  graph: Graph;
  /**
   *
   * @type {Vertex}
   * @memberof GVertex
   */
  vertex: Vertex;
}

/**
 * Check if a given object implements the GVertex interface.
 */
export function instanceOfGVertex(value: object): value is GVertex {
  if (!("graph" in value) || value.graph === undefined) {
    return false;
  }
  if (!("vertex" in value) || value.vertex === undefined) {
    return false;
  }
  return true;
}

export function GVertexFromJSON(json: any): GVertex {
  return GVertexFromJSONTyped(json, false);
}

export function GVertexFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): GVertex {
  if (json == null) {
    return json;
  }
  return {
    graph: GraphFromJSON(json.graph),
    vertex: VertexFromJSON(json.vertex),
  };
}

export function GVertexToJSON(json: any): GVertex {
  return GVertexToJSONTyped(json, false);
}

export function GVertexToJSONTyped(
  value?: GVertex | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    graph: GraphToJSON(value.graph),
    vertex: VertexToJSON(value.vertex),
  };
}
