/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface NameUnit
 */
export interface NameUnit {
  /**
   *
   * @type {string}
   * @memberof NameUnit
   */
  type: NameUnitTypeEnum;
}

/**
 * @export
 */
export const NameUnitTypeEnum = {
  Wildcard: "Wildcard",
} as const;
export type NameUnitTypeEnum = (typeof NameUnitTypeEnum)[keyof typeof NameUnitTypeEnum];

/**
 * Check if a given object implements the NameUnit interface.
 */
export function instanceOfNameUnit(value: object): value is NameUnit {
  if (!("type" in value) || value.type === undefined) {
    return false;
  }
  return true;
}

export function NameUnitFromJSON(json: any): NameUnit {
  return NameUnitFromJSONTyped(json, false);
}

export function NameUnitFromJSONTyped(json: any, _ignoreDiscriminator: boolean): NameUnit {
  if (json == null) {
    return json;
  }
  return {
    type: json.type,
  };
}

export function NameUnitToJSON(json: any): NameUnit {
  return NameUnitToJSONTyped(json, false);
}

export function NameUnitToJSONTyped(
  value?: NameUnit | null,
  _ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value.type,
  };
}
