/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Vertex } from "./Vertex";

import { VertexFromJSON, VertexToJSON } from "./Vertex";

/**
 *
 * @export
 * @interface NameNQuoteVertex
 */
export interface NameNQuoteVertex {
  /**
   *
   * @type {string}
   * @memberof NameNQuoteVertex
   */
  type: NameNQuoteVertexTypeEnum;
  /**
   *
   * @type {Vertex}
   * @memberof NameNQuoteVertex
   */
  value: Vertex;
}

/**
 * @export
 */
export const NameNQuoteVertexTypeEnum = {
  QuoteVertex: "QuoteVertex",
} as const;
export type NameNQuoteVertexTypeEnum =
  (typeof NameNQuoteVertexTypeEnum)[keyof typeof NameNQuoteVertexTypeEnum];

/**
 * Check if a given object implements the NameNQuoteVertex interface.
 */
export function instanceOfNameNQuoteVertex(
  value: object,
): value is NameNQuoteVertex {
  if (!("value" in value) || value.value === undefined) {
    return false;
  }
  if (!("type" in value) || value.type === undefined) {
    return false;
  }
  return true;
}

export function NameNQuoteVertexFromJSON(json: any): NameNQuoteVertex {
  return NameNQuoteVertexFromJSONTyped(json, false);
}

export function NameNQuoteVertexFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NameNQuoteVertex {
  if (json == null) {
    return json;
  }
  return {
    type: json.type,
    value: VertexFromJSON(json.value),
  };
}

export function NameNQuoteVertexToJSON(json: any): NameNQuoteVertex {
  return NameNQuoteVertexToJSONTyped(json, false);
}

export function NameNQuoteVertexToJSONTyped(
  value?: NameNQuoteVertex | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value.type,
    value: VertexToJSON(value.value),
  };
}
