/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Graph } from "./Graph";

import { GraphFromJSON, GraphToJSON } from "./Graph";

/**
 *
 * @export
 * @interface NameNQuoteGraph
 */
export interface NameNQuoteGraph {
  /**
   *
   * @type {string}
   * @memberof NameNQuoteGraph
   */
  type: NameNQuoteGraphTypeEnum;
  /**
   *
   * @type {Graph}
   * @memberof NameNQuoteGraph
   */
  value: Graph;
}

/**
 * @export
 */
export const NameNQuoteGraphTypeEnum = {
  QuoteGraph: "QuoteGraph",
} as const;
export type NameNQuoteGraphTypeEnum =
  (typeof NameNQuoteGraphTypeEnum)[keyof typeof NameNQuoteGraphTypeEnum];

/**
 * Check if a given object implements the NameNQuoteGraph interface.
 */
export function instanceOfNameNQuoteGraph(
  value: object,
): value is NameNQuoteGraph {
  if (!("value" in value) || value.value === undefined) {
    return false;
  }
  if (!("type" in value) || value.type === undefined) {
    return false;
  }
  return true;
}

export function NameNQuoteGraphFromJSON(json: any): NameNQuoteGraph {
  return NameNQuoteGraphFromJSONTyped(json, false);
}

export function NameNQuoteGraphFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NameNQuoteGraph {
  if (json == null) {
    return json;
  }
  return {
    type: json.type,
    value: GraphFromJSON(json.value),
  };
}

export function NameNQuoteGraphToJSON(json: any): NameNQuoteGraph {
  return NameNQuoteGraphToJSONTyped(json, false);
}

export function NameNQuoteGraphToJSONTyped(
  value?: NameNQuoteGraph | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value.type,
    value: GraphToJSON(value.value),
  };
}
