/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface NameNVVar
 */
export interface NameNVVar {
  /**
   *
   * @type {string}
   * @memberof NameNVVar
   */
  type: NameNVVarTypeEnum;
  /**
   *
   * @type {string}
   * @memberof NameNVVar
   */
  value: string;
}

/**
 * @export
 */
export const NameNVVarTypeEnum = {
  VVar: "VVar",
} as const;
export type NameNVVarTypeEnum = (typeof NameNVVarTypeEnum)[keyof typeof NameNVVarTypeEnum];

/**
 * Check if a given object implements the NameNVVar interface.
 */
export function instanceOfNameNVVar(value: object): value is NameNVVar {
  if (!("value" in value) || value.value === undefined) {
    return false;
  }
  if (!("type" in value) || value.type === undefined) {
    return false;
  }
  return true;
}

export function NameNVVarFromJSON(json: any): NameNVVar {
  return NameNVVarFromJSONTyped(json, false);
}

export function NameNVVarFromJSONTyped(json: any, ignoreDiscriminator: boolean): NameNVVar {
  if (json == null) {
    return json;
  }
  return {
    type: json.type,
    value: json.value,
  };
}

export function NameNVVarToJSON(json: any): NameNVVar {
  return NameNVVarToJSONTyped(json, false);
}

export function NameNVVarToJSONTyped(
  value?: NameNVVar | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    type: value.type,
    value: value.value,
  };
}
