/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Vertex } from "./Vertex";

import { VertexFromJSON, VertexToJSON } from "./Vertex";

/**
 *
 * @export
 * @interface NQuoteVertex
 */
export interface NQuoteVertex {
  /**
   *
   * @type {Vertex}
   * @memberof NQuoteVertex
   */
  value: Vertex;
}

/**
 * Check if a given object implements the NQuoteVertex interface.
 */
export function instanceOfNQuoteVertex(value: object): value is NQuoteVertex {
  if (!("value" in value) || value.value === undefined) {
    return false;
  }
  return true;
}

export function NQuoteVertexFromJSON(json: any): NQuoteVertex {
  return NQuoteVertexFromJSONTyped(json, false);
}

export function NQuoteVertexFromJSONTyped(json: any, _ignoreDiscriminator: boolean): NQuoteVertex {
  if (json == null) {
    return json;
  }
  return {
    value: VertexFromJSON(json.value),
  };
}

export function NQuoteVertexToJSON(json: any): NQuoteVertex {
  return NQuoteVertexToJSONTyped(json, false);
}

export function NQuoteVertexToJSONTyped(
  value?: NQuoteVertex | null,
  _ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    value: VertexToJSON(value.value),
  };
}
