/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface NVVar
 */
export interface NVVar {
  /**
   *
   * @type {string}
   * @memberof NVVar
   */
  value: string;
}

/**
 * Check if a given object implements the NVVar interface.
 */
export function instanceOfNVVar(value: object): value is NVVar {
  if (!("value" in value) || value.value === undefined) {
    return false;
  }
  return true;
}

export function NVVarFromJSON(json: any): NVVar {
  return NVVarFromJSONTyped(json, false);
}

export function NVVarFromJSONTyped(json: any, ignoreDiscriminator: boolean): NVVar {
  if (json == null) {
    return json;
  }
  return {
    value: json.value,
  };
}

export function NVVarToJSON(json: any): NVVar {
  return NVVarToJSONTyped(json, false);
}

export function NVVarToJSONTyped(value?: NVVar | null, ignoreDiscriminator: boolean = false): any {
  if (value == null) {
    return value;
  }

  return {
    value: value.value,
  };
}
