/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TimestampMillis } from "./TimestampMillis";

import {
  TimestampMillisFromJSON,
  TimestampMillisToJSON,
} from "./TimestampMillis";

/**
 *
 * @export
 * @interface OslfHeader
 */
export interface OslfHeader {
  /**
   *
   * @type {TimestampMillis}
   * @memberof OslfHeader
   */
  createdAt: TimestampMillis;
  /**
   *
   * @type {string}
   * @memberof OslfHeader
   */
  description?: string;
  /**
   *
   * @type {string}
   * @memberof OslfHeader
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof OslfHeader
   */
  name: string;
  /**
   *
   * @type {string}
   * @memberof OslfHeader
   */
  version: string;
}

/**
 * Check if a given object implements the OslfHeader interface.
 */
export function instanceOfOslfHeader(value: object): value is OslfHeader {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("createdAt" in value) || value.createdAt === undefined) {
    return false;
  }
  if (!("name" in value) || value.name === undefined) {
    return false;
  }
  return true;
}

export function OslfHeaderFromJSON(json: any): OslfHeader {
  return OslfHeaderFromJSONTyped(json, false);
}

export function OslfHeaderFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): OslfHeader {
  if (json == null) {
    return json;
  }
  return {
    createdAt: TimestampMillisFromJSON(json.created_at),
    description: json.description == null ? undefined : json.description,
    id: json.id,
    name: json.name,
    version: json.version,
  };
}

export function OslfHeaderToJSON(json: any): OslfHeader {
  return OslfHeaderToJSONTyped(json, false);
}

export function OslfHeaderToJSONTyped(
  value?: OslfHeader | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    created_at: TimestampMillisToJSON(value.createdAt),
    description: value.description,
    id: value.id,
    name: value.name,
    version: value.version,
  };
}
