/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Oslf } from "./Oslf";

import { OslfFromJSON, OslfToJSON } from "./Oslf";

/**
 *
 * @export
 * @interface Oslfs
 */
export interface Oslfs {
  /**
   *
   * @type {Array<Oslf>}
   * @memberof Oslfs
   */
  oslfs: Array<Oslf>;
}

/**
 * Check if a given object implements the Oslfs interface.
 */
export function instanceOfOslfs(value: object): value is Oslfs {
  if (!("oslfs" in value) || value.oslfs === undefined) {
    return false;
  }
  return true;
}

export function OslfsFromJSON(json: any): Oslfs {
  return OslfsFromJSONTyped(json, false);
}

export function OslfsFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Oslfs {
  if (json == null) {
    return json;
  }
  return {
    oslfs: (json.oslfs as Array<any>).map(OslfFromJSON),
  };
}

export function OslfsToJSON(json: any): Oslfs {
  return OslfsToJSONTyped(json, false);
}

export function OslfsToJSONTyped(
  value?: Oslfs | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    oslfs: (value.oslfs as Array<any>).map(OslfToJSON),
  };
}
