/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 *
 * @export
 * @interface PostRef
 */
export interface PostRef {
  /**
   *
   * @type {string}
   * @memberof PostRef
   */
  cid: string;
  /**
   *
   * @type {string}
   * @memberof PostRef
   */
  uri: string;
}

/**
 * Check if a given object implements the PostRef interface.
 */
export function instanceOfPostRef(value: object): value is PostRef {
  if (!("cid" in value) || value.cid === undefined) {
    return false;
  }
  if (!("uri" in value) || value.uri === undefined) {
    return false;
  }
  return true;
}

export function PostRefFromJSON(json: any): PostRef {
  return PostRefFromJSONTyped(json, false);
}

export function PostRefFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PostRef {
  if (json == null) {
    return json;
  }
  return {
    cid: json.cid,
    uri: json.uri,
  };
}

export function PostRefToJSON(json: any): PostRef {
  return PostRefToJSONTyped(json, false);
}

export function PostRefToJSONTyped(
  value?: PostRef | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    cid: value.cid,
    uri: value.uri,
  };
}
