/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateAgentResp } from "./CreateAgentResp";

import {
  CreateAgentRespFromJSON,
  CreateAgentRespToJSON,
} from "./CreateAgentResp";

/**
 *
 * @export
 * @interface PrepareResponseCreateAgentResp
 */
export interface PrepareResponseCreateAgentResp {
  /**
   *
   * @type {CreateAgentResp}
   * @memberof PrepareResponseCreateAgentResp
   */
  response: CreateAgentResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponseCreateAgentResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponseCreateAgentResp interface.
 */
export function instanceOfPrepareResponseCreateAgentResp(
  value: object,
): value is PrepareResponseCreateAgentResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponseCreateAgentRespFromJSON(
  json: any,
): PrepareResponseCreateAgentResp {
  return PrepareResponseCreateAgentRespFromJSONTyped(json, false);
}

export function PrepareResponseCreateAgentRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponseCreateAgentResp {
  if (json == null) {
    return json;
  }
  return {
    response: CreateAgentRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponseCreateAgentRespToJSON(
  json: any,
): PrepareResponseCreateAgentResp {
  return PrepareResponseCreateAgentRespToJSONTyped(json, false);
}

export function PrepareResponseCreateAgentRespToJSONTyped(
  value?: PrepareResponseCreateAgentResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: CreateAgentRespToJSON(value.response),
    token: value.token,
  };
}
