/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PublishToFireskyResp } from "./PublishToFireskyResp";

import {
  PublishToFireskyRespFromJSON,
  PublishToFireskyRespToJSON,
} from "./PublishToFireskyResp";

/**
 *
 * @export
 * @interface PrepareResponsePublishToFireskyResp
 */
export interface PrepareResponsePublishToFireskyResp {
  /**
   *
   * @type {PublishToFireskyResp}
   * @memberof PrepareResponsePublishToFireskyResp
   */
  response: PublishToFireskyResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponsePublishToFireskyResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponsePublishToFireskyResp interface.
 */
export function instanceOfPrepareResponsePublishToFireskyResp(
  value: object,
): value is PrepareResponsePublishToFireskyResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponsePublishToFireskyRespFromJSON(
  json: any,
): PrepareResponsePublishToFireskyResp {
  return PrepareResponsePublishToFireskyRespFromJSONTyped(json, false);
}

export function PrepareResponsePublishToFireskyRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponsePublishToFireskyResp {
  if (json == null) {
    return json;
  }
  return {
    response: PublishToFireskyRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponsePublishToFireskyRespToJSON(
  json: any,
): PrepareResponsePublishToFireskyResp {
  return PrepareResponsePublishToFireskyRespToJSONTyped(json, false);
}

export function PrepareResponsePublishToFireskyRespToJSONTyped(
  value?: PrepareResponsePublishToFireskyResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: PublishToFireskyRespToJSON(value.response),
    token: value.token,
  };
}
