/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SaveOslfResp } from "./SaveOslfResp";

import { SaveOslfRespFromJSON, SaveOslfRespToJSON } from "./SaveOslfResp";

/**
 *
 * @export
 * @interface PrepareResponseSaveOslfResp
 */
export interface PrepareResponseSaveOslfResp {
  /**
   *
   * @type {SaveOslfResp}
   * @memberof PrepareResponseSaveOslfResp
   */
  response: SaveOslfResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponseSaveOslfResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponseSaveOslfResp interface.
 */
export function instanceOfPrepareResponseSaveOslfResp(
  value: object,
): value is PrepareResponseSaveOslfResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponseSaveOslfRespFromJSON(
  json: any,
): PrepareResponseSaveOslfResp {
  return PrepareResponseSaveOslfRespFromJSONTyped(json, false);
}

export function PrepareResponseSaveOslfRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponseSaveOslfResp {
  if (json == null) {
    return json;
  }
  return {
    response: SaveOslfRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponseSaveOslfRespToJSON(
  json: any,
): PrepareResponseSaveOslfResp {
  return PrepareResponseSaveOslfRespToJSONTyped(json, false);
}

export function PrepareResponseSaveOslfRespToJSONTyped(
  value?: PrepareResponseSaveOslfResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: SaveOslfRespToJSON(value.response),
    token: value.token,
  };
}
