/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DeployAgentsTeamResp } from "./DeployAgentsTeamResp";

import {
  DeployAgentsTeamRespFromJSON,
  DeployAgentsTeamRespToJSON,
} from "./DeployAgentsTeamResp";

/**
 *
 * @export
 * @interface PrepareResponseDeployAgentsTeamResp
 */
export interface PrepareResponseDeployAgentsTeamResp {
  /**
   *
   * @type {DeployAgentsTeamResp}
   * @memberof PrepareResponseDeployAgentsTeamResp
   */
  response: DeployAgentsTeamResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponseDeployAgentsTeamResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponseDeployAgentsTeamResp interface.
 */
export function instanceOfPrepareResponseDeployAgentsTeamResp(
  value: object,
): value is PrepareResponseDeployAgentsTeamResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponseDeployAgentsTeamRespFromJSON(
  json: any,
): PrepareResponseDeployAgentsTeamResp {
  return PrepareResponseDeployAgentsTeamRespFromJSONTyped(json, false);
}

export function PrepareResponseDeployAgentsTeamRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponseDeployAgentsTeamResp {
  if (json == null) {
    return json;
  }
  return {
    response: DeployAgentsTeamRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponseDeployAgentsTeamRespToJSON(
  json: any,
): PrepareResponseDeployAgentsTeamResp {
  return PrepareResponseDeployAgentsTeamRespToJSONTyped(json, false);
}

export function PrepareResponseDeployAgentsTeamRespToJSONTyped(
  value?: PrepareResponseDeployAgentsTeamResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: DeployAgentsTeamRespToJSON(value.response),
    token: value.token,
  };
}
