/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SaveAgentsTeamResp } from "./SaveAgentsTeamResp";

import {
  SaveAgentsTeamRespFromJSON,
  SaveAgentsTeamRespToJSON,
} from "./SaveAgentsTeamResp";

/**
 *
 * @export
 * @interface PrepareResponseSaveAgentsTeamResp
 */
export interface PrepareResponseSaveAgentsTeamResp {
  /**
   *
   * @type {SaveAgentsTeamResp}
   * @memberof PrepareResponseSaveAgentsTeamResp
   */
  response: SaveAgentsTeamResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponseSaveAgentsTeamResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponseSaveAgentsTeamResp interface.
 */
export function instanceOfPrepareResponseSaveAgentsTeamResp(
  value: object,
): value is PrepareResponseSaveAgentsTeamResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponseSaveAgentsTeamRespFromJSON(
  json: any,
): PrepareResponseSaveAgentsTeamResp {
  return PrepareResponseSaveAgentsTeamRespFromJSONTyped(json, false);
}

export function PrepareResponseSaveAgentsTeamRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponseSaveAgentsTeamResp {
  if (json == null) {
    return json;
  }
  return {
    response: SaveAgentsTeamRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponseSaveAgentsTeamRespToJSON(
  json: any,
): PrepareResponseSaveAgentsTeamResp {
  return PrepareResponseSaveAgentsTeamRespToJSONTyped(json, false);
}

export function PrepareResponseSaveAgentsTeamRespToJSONTyped(
  value?: PrepareResponseSaveAgentsTeamResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: SaveAgentsTeamRespToJSON(value.response),
    token: value.token,
  };
}
