/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DeployAgentResp } from "./DeployAgentResp";

import {
  DeployAgentRespFromJSON,
  DeployAgentRespToJSON,
} from "./DeployAgentResp";

/**
 *
 * @export
 * @interface PrepareResponseDeployAgentResp
 */
export interface PrepareResponseDeployAgentResp {
  /**
   *
   * @type {DeployAgentResp}
   * @memberof PrepareResponseDeployAgentResp
   */
  response: DeployAgentResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponseDeployAgentResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponseDeployAgentResp interface.
 */
export function instanceOfPrepareResponseDeployAgentResp(
  value: object,
): value is PrepareResponseDeployAgentResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponseDeployAgentRespFromJSON(
  json: any,
): PrepareResponseDeployAgentResp {
  return PrepareResponseDeployAgentRespFromJSONTyped(json, false);
}

export function PrepareResponseDeployAgentRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponseDeployAgentResp {
  if (json == null) {
    return json;
  }
  return {
    response: DeployAgentRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponseDeployAgentRespToJSON(
  json: any,
): PrepareResponseDeployAgentResp {
  return PrepareResponseDeployAgentRespToJSONTyped(json, false);
}

export function PrepareResponseDeployAgentRespToJSONTyped(
  value?: PrepareResponseDeployAgentResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: DeployAgentRespToJSON(value.response),
    token: value.token,
  };
}
