/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DeployTestResp } from "./DeployTestResp";

import { DeployTestRespFromJSON, DeployTestRespToJSON } from "./DeployTestResp";

/**
 *
 * @export
 * @interface PrepareResponseDeployTestResp
 */
export interface PrepareResponseDeployTestResp {
  /**
   *
   * @type {DeployTestResp}
   * @memberof PrepareResponseDeployTestResp
   */
  response: DeployTestResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponseDeployTestResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponseDeployTestResp interface.
 */
export function instanceOfPrepareResponseDeployTestResp(
  value: object,
): value is PrepareResponseDeployTestResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponseDeployTestRespFromJSON(
  json: any,
): PrepareResponseDeployTestResp {
  return PrepareResponseDeployTestRespFromJSONTyped(json, false);
}

export function PrepareResponseDeployTestRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponseDeployTestResp {
  if (json == null) {
    return json;
  }
  return {
    response: DeployTestRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponseDeployTestRespToJSON(
  json: any,
): PrepareResponseDeployTestResp {
  return PrepareResponseDeployTestRespToJSONTyped(json, false);
}

export function PrepareResponseDeployTestRespToJSONTyped(
  value?: PrepareResponseDeployTestResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: DeployTestRespToJSON(value.response),
    token: value.token,
  };
}
