/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RunAgentsTeamResp } from "./RunAgentsTeamResp";

import {
  RunAgentsTeamRespFromJSON,
  RunAgentsTeamRespToJSON,
} from "./RunAgentsTeamResp";

/**
 *
 * @export
 * @interface PrepareResponseRunAgentsTeamResp
 */
export interface PrepareResponseRunAgentsTeamResp {
  /**
   *
   * @type {RunAgentsTeamResp}
   * @memberof PrepareResponseRunAgentsTeamResp
   */
  response: RunAgentsTeamResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponseRunAgentsTeamResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponseRunAgentsTeamResp interface.
 */
export function instanceOfPrepareResponseRunAgentsTeamResp(
  value: object,
): value is PrepareResponseRunAgentsTeamResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponseRunAgentsTeamRespFromJSON(
  json: any,
): PrepareResponseRunAgentsTeamResp {
  return PrepareResponseRunAgentsTeamRespFromJSONTyped(json, false);
}

export function PrepareResponseRunAgentsTeamRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponseRunAgentsTeamResp {
  if (json == null) {
    return json;
  }
  return {
    response: RunAgentsTeamRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponseRunAgentsTeamRespToJSON(
  json: any,
): PrepareResponseRunAgentsTeamResp {
  return PrepareResponseRunAgentsTeamRespToJSONTyped(json, false);
}

export function PrepareResponseRunAgentsTeamRespToJSONTyped(
  value?: PrepareResponseRunAgentsTeamResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: RunAgentsTeamRespToJSON(value.response),
    token: value.token,
  };
}
