/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BoostResp } from "./BoostResp";

import { BoostRespFromJSON, BoostRespToJSON } from "./BoostResp";

/**
 *
 * @export
 * @interface PrepareResponseBoostResp
 */
export interface PrepareResponseBoostResp {
  /**
   *
   * @type {BoostResp}
   * @memberof PrepareResponseBoostResp
   */
  response: BoostResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponseBoostResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponseBoostResp interface.
 */
export function instanceOfPrepareResponseBoostResp(
  value: object,
): value is PrepareResponseBoostResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponseBoostRespFromJSON(
  json: any,
): PrepareResponseBoostResp {
  return PrepareResponseBoostRespFromJSONTyped(json, false);
}

export function PrepareResponseBoostRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponseBoostResp {
  if (json == null) {
    return json;
  }
  return {
    response: BoostRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponseBoostRespToJSON(
  json: any,
): PrepareResponseBoostResp {
  return PrepareResponseBoostRespToJSONTyped(json, false);
}

export function PrepareResponseBoostRespToJSONTyped(
  value?: PrepareResponseBoostResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: BoostRespToJSON(value.response),
    token: value.token,
  };
}
