/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateResp } from "./CreateResp";

import { CreateRespFromJSON, CreateRespToJSON } from "./CreateResp";

/**
 *
 * @export
 * @interface PrepareResponseCreateResp
 */
export interface PrepareResponseCreateResp {
  /**
   *
   * @type {CreateResp}
   * @memberof PrepareResponseCreateResp
   */
  response: CreateResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponseCreateResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponseCreateResp interface.
 */
export function instanceOfPrepareResponseCreateResp(
  value: object,
): value is PrepareResponseCreateResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponseCreateRespFromJSON(
  json: any,
): PrepareResponseCreateResp {
  return PrepareResponseCreateRespFromJSONTyped(json, false);
}

export function PrepareResponseCreateRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponseCreateResp {
  if (json == null) {
    return json;
  }
  return {
    response: CreateRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponseCreateRespToJSON(
  json: any,
): PrepareResponseCreateResp {
  return PrepareResponseCreateRespToJSONTyped(json, false);
}

export function PrepareResponseCreateRespToJSONTyped(
  value?: PrepareResponseCreateResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: CreateRespToJSON(value.response),
    token: value.token,
  };
}
