/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { TransferResp } from "./TransferResp";

import { TransferRespFromJSON, TransferRespToJSON } from "./TransferResp";

/**
 *
 * @export
 * @interface PrepareResponseTransferResp
 */
export interface PrepareResponseTransferResp {
  /**
   *
   * @type {TransferResp}
   * @memberof PrepareResponseTransferResp
   */
  response: TransferResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponseTransferResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponseTransferResp interface.
 */
export function instanceOfPrepareResponseTransferResp(
  value: object,
): value is PrepareResponseTransferResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponseTransferRespFromJSON(
  json: any,
): PrepareResponseTransferResp {
  return PrepareResponseTransferRespFromJSONTyped(json, false);
}

export function PrepareResponseTransferRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponseTransferResp {
  if (json == null) {
    return json;
  }
  return {
    response: TransferRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponseTransferRespToJSON(
  json: any,
): PrepareResponseTransferResp {
  return PrepareResponseTransferRespToJSONTyped(json, false);
}

export function PrepareResponseTransferRespToJSONTyped(
  value?: PrepareResponseTransferResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: TransferRespToJSON(value.response),
    token: value.token,
  };
}
