/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SaveResp } from "./SaveResp";

import { SaveRespFromJSON, SaveRespToJSON } from "./SaveResp";

/**
 *
 * @export
 * @interface PrepareResponseSaveResp
 */
export interface PrepareResponseSaveResp {
  /**
   *
   * @type {SaveResp}
   * @memberof PrepareResponseSaveResp
   */
  response: SaveResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponseSaveResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponseSaveResp interface.
 */
export function instanceOfPrepareResponseSaveResp(
  value: object,
): value is PrepareResponseSaveResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponseSaveRespFromJSON(
  json: any,
): PrepareResponseSaveResp {
  return PrepareResponseSaveRespFromJSONTyped(json, false);
}

export function PrepareResponseSaveRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponseSaveResp {
  if (json == null) {
    return json;
  }
  return {
    response: SaveRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponseSaveRespToJSON(
  json: any,
): PrepareResponseSaveResp {
  return PrepareResponseSaveRespToJSONTyped(json, false);
}

export function PrepareResponseSaveRespToJSONTyped(
  value?: PrepareResponseSaveResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: SaveRespToJSON(value.response),
    token: value.token,
  };
}
