/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateOslfResp } from "./CreateOslfResp";

import { CreateOslfRespFromJSON, CreateOslfRespToJSON } from "./CreateOslfResp";

/**
 *
 * @export
 * @interface PrepareResponseCreateOslfResp
 */
export interface PrepareResponseCreateOslfResp {
  /**
   *
   * @type {CreateOslfResp}
   * @memberof PrepareResponseCreateOslfResp
   */
  response: CreateOslfResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponseCreateOslfResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponseCreateOslfResp interface.
 */
export function instanceOfPrepareResponseCreateOslfResp(
  value: object,
): value is PrepareResponseCreateOslfResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponseCreateOslfRespFromJSON(
  json: any,
): PrepareResponseCreateOslfResp {
  return PrepareResponseCreateOslfRespFromJSONTyped(json, false);
}

export function PrepareResponseCreateOslfRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponseCreateOslfResp {
  if (json == null) {
    return json;
  }
  return {
    response: CreateOslfRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponseCreateOslfRespToJSON(
  json: any,
): PrepareResponseCreateOslfResp {
  return PrepareResponseCreateOslfRespToJSONTyped(json, false);
}

export function PrepareResponseCreateOslfRespToJSONTyped(
  value?: PrepareResponseCreateOslfResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: CreateOslfRespToJSON(value.response),
    token: value.token,
  };
}
