/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PublishAgentsTeamToFireskyResp } from "./PublishAgentsTeamToFireskyResp";

import {
  PublishAgentsTeamToFireskyRespFromJSON,
  PublishAgentsTeamToFireskyRespToJSON,
} from "./PublishAgentsTeamToFireskyResp";

/**
 *
 * @export
 * @interface PrepareResponsePublishAgentsTeamToFireskyResp
 */
export interface PrepareResponsePublishAgentsTeamToFireskyResp {
  /**
   *
   * @type {PublishAgentsTeamToFireskyResp}
   * @memberof PrepareResponsePublishAgentsTeamToFireskyResp
   */
  response: PublishAgentsTeamToFireskyResp;
  /**
   *
   * @type {string}
   * @memberof PrepareResponsePublishAgentsTeamToFireskyResp
   */
  token: string;
}

/**
 * Check if a given object implements the PrepareResponsePublishAgentsTeamToFireskyResp interface.
 */
export function instanceOfPrepareResponsePublishAgentsTeamToFireskyResp(
  value: object,
): value is PrepareResponsePublishAgentsTeamToFireskyResp {
  if (!("response" in value) || value.response === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function PrepareResponsePublishAgentsTeamToFireskyRespFromJSON(
  json: any,
): PrepareResponsePublishAgentsTeamToFireskyResp {
  return PrepareResponsePublishAgentsTeamToFireskyRespFromJSONTyped(
    json,
    false,
  );
}

export function PrepareResponsePublishAgentsTeamToFireskyRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PrepareResponsePublishAgentsTeamToFireskyResp {
  if (json == null) {
    return json;
  }
  return {
    response: PublishAgentsTeamToFireskyRespFromJSON(json.response),
    token: json.token,
  };
}

export function PrepareResponsePublishAgentsTeamToFireskyRespToJSON(
  json: any,
): PrepareResponsePublishAgentsTeamToFireskyResp {
  return PrepareResponsePublishAgentsTeamToFireskyRespToJSONTyped(json, false);
}

export function PrepareResponsePublishAgentsTeamToFireskyRespToJSONTyped(
  value?: PrepareResponsePublishAgentsTeamToFireskyResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    response: PublishAgentsTeamToFireskyRespToJSON(value.response),
    token: value.token,
  };
}
