/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Base64 } from "./Base64";

import { Base64FromJSON, Base64ToJSON } from "./Base64";

/**
 *
 * @export
 * @interface PublishAgentsTeamToFireskyResp
 */
export interface PublishAgentsTeamToFireskyResp {
  /**
   *
   * @type {Base64}
   * @memberof PublishAgentsTeamToFireskyResp
   */
  contract: Base64;
}

/**
 * Check if a given object implements the PublishAgentsTeamToFireskyResp interface.
 */
export function instanceOfPublishAgentsTeamToFireskyResp(
  value: object,
): value is PublishAgentsTeamToFireskyResp {
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  return true;
}

export function PublishAgentsTeamToFireskyRespFromJSON(
  json: any,
): PublishAgentsTeamToFireskyResp {
  return PublishAgentsTeamToFireskyRespFromJSONTyped(json, false);
}

export function PublishAgentsTeamToFireskyRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PublishAgentsTeamToFireskyResp {
  if (json == null) {
    return json;
  }
  return {
    contract: Base64FromJSON(json.contract),
  };
}

export function PublishAgentsTeamToFireskyRespToJSON(
  json: any,
): PublishAgentsTeamToFireskyResp {
  return PublishAgentsTeamToFireskyRespToJSONTyped(json, false);
}

export function PublishAgentsTeamToFireskyRespToJSONTyped(
  value?: PublishAgentsTeamToFireskyResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: Base64ToJSON(value.contract),
  };
}
