/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Base64 } from "./Base64";

import { Base64FromJSON, Base64ToJSON } from "./Base64";

/**
 *
 * @export
 * @interface PublishToFireskyResp
 */
export interface PublishToFireskyResp {
  /**
   *
   * @type {Base64}
   * @memberof PublishToFireskyResp
   */
  contract: Base64;
}

/**
 * Check if a given object implements the PublishToFireskyResp interface.
 */
export function instanceOfPublishToFireskyResp(
  value: object,
): value is PublishToFireskyResp {
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  return true;
}

export function PublishToFireskyRespFromJSON(json: any): PublishToFireskyResp {
  return PublishToFireskyRespFromJSONTyped(json, false);
}

export function PublishToFireskyRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): PublishToFireskyResp {
  if (json == null) {
    return json;
  }
  return {
    contract: Base64FromJSON(json.contract),
  };
}

export function PublishToFireskyRespToJSON(json: any): PublishToFireskyResp {
  return PublishToFireskyRespToJSONTyped(json, false);
}

export function PublishToFireskyRespToJSONTyped(
  value?: PublishToFireskyResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: Base64ToJSON(value.contract),
  };
}
