/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Base64 } from "./Base64";
import type { Int64 } from "./Int64";
import type { PublicKey } from "./PublicKey";
import type { TimestampMillis } from "./TimestampMillis";

import { Base64FromJSON, Base64ToJSON } from "./Base64";
import { Int64FromJSON, Int64ToJSON } from "./Int64";
import { PublicKeyFromJSON, PublicKeyToJSON } from "./PublicKey";
import {
  TimestampMillisFromJSON,
  TimestampMillisToJSON,
} from "./TimestampMillis";

/**
 *
 * @export
 * @interface RegistryDeploy
 */
export interface RegistryDeploy {
  /**
   *
   * @type {Base64}
   * @memberof RegistryDeploy
   */
  signature: Base64;
  /**
   *
   * @type {TimestampMillis}
   * @memberof RegistryDeploy
   */
  timestamp: TimestampMillis;
  /**
   *
   * @type {PublicKey}
   * @memberof RegistryDeploy
   */
  uriPubKey: PublicKey;
  /**
   *
   * @type {Int64}
   * @memberof RegistryDeploy
   */
  version: Int64;
}

/**
 * Check if a given object implements the RegistryDeploy interface.
 */
export function instanceOfRegistryDeploy(
  value: object,
): value is RegistryDeploy {
  if (!("timestamp" in value) || value.timestamp === undefined) {
    return false;
  }
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("uriPubKey" in value) || value.uriPubKey === undefined) {
    return false;
  }
  if (!("signature" in value) || value.signature === undefined) {
    return false;
  }
  return true;
}

export function RegistryDeployFromJSON(json: any): RegistryDeploy {
  return RegistryDeployFromJSONTyped(json, false);
}

export function RegistryDeployFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): RegistryDeploy {
  if (json == null) {
    return json;
  }
  return {
    signature: Base64FromJSON(json.signature),
    timestamp: TimestampMillisFromJSON(json.timestamp),
    uriPubKey: PublicKeyFromJSON(json.uri_pub_key),
    version: Int64FromJSON(json.version),
  };
}

export function RegistryDeployToJSON(json: any): RegistryDeploy {
  return RegistryDeployToJSONTyped(json, false);
}

export function RegistryDeployToJSONTyped(
  value?: RegistryDeploy | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    signature: Base64ToJSON(value.signature),
    timestamp: TimestampMillisToJSON(value.timestamp),
    uri_pub_key: PublicKeyToJSON(value.uriPubKey),
    version: Int64ToJSON(value.version),
  };
}
