/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Int64 } from "./Int64";
import type { RequestStatus } from "./RequestStatus";
import type { TimestampMillis } from "./TimestampMillis";

import { Int64FromJSON, Int64ToJSON } from "./Int64";
import { RequestStatusFromJSON, RequestStatusToJSON } from "./RequestStatus";
import {
  TimestampMillisFromJSON,
  TimestampMillisToJSON,
} from "./TimestampMillis";

/**
 *
 * @export
 * @interface Request
 */
export interface Request {
  /**
   *
   * @type {Int64}
   * @memberof Request
   */
  amount: Int64;
  /**
   *
   * @type {string}
   * @memberof Request
   */
  id: string;
  /**
   *
   * @type {RequestStatus}
   * @memberof Request
   */
  status: RequestStatus;
  /**
   *
   * @type {TimestampMillis}
   * @memberof Request
   */
  timestamp: TimestampMillis;
}

/**
 * Check if a given object implements the Request interface.
 */
export function instanceOfRequest(value: object): value is Request {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("timestamp" in value) || value.timestamp === undefined) {
    return false;
  }
  if (!("amount" in value) || value.amount === undefined) {
    return false;
  }
  if (!("status" in value) || value.status === undefined) {
    return false;
  }
  return true;
}

export function RequestFromJSON(json: any): Request {
  return RequestFromJSONTyped(json, false);
}

export function RequestFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Request {
  if (json == null) {
    return json;
  }
  return {
    amount: Int64FromJSON(json.amount),
    id: json.id,
    status: RequestStatusFromJSON(json.status),
    timestamp: TimestampMillisFromJSON(json.timestamp),
  };
}

export function RequestToJSON(json: any): Request {
  return RequestToJSONTyped(json, false);
}

export function RequestToJSONTyped(
  value?: Request | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amount: Int64ToJSON(value.amount),
    id: value.id,
    status: RequestStatusToJSON(value.status),
    timestamp: TimestampMillisToJSON(value.timestamp),
  };
}
