/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RequestStatus } from "./RequestStatus";
import { RequestStatusFromJSON, RequestStatusToJSON } from "./RequestStatus";
import type { UInt64 } from "./UInt64";
import { UInt64FromJSON, UInt64ToJSON } from "./UInt64";
import type { UnixTimestamp } from "./UnixTimestamp";
import { UnixTimestampFromJSON, UnixTimestampToJSON } from "./UnixTimestamp";

/**
 *
 * @export
 * @interface Request
 */
export interface Request {
  /**
   *
   * @type {UInt64}
   * @memberof Request
   */
  amount: UInt64;
  /**
   *
   * @type {UnixTimestamp}
   * @memberof Request
   */
  date: UnixTimestamp;
  /**
   *
   * @type {string}
   * @memberof Request
   */
  id: string;
  /**
   *
   * @type {RequestStatus}
   * @memberof Request
   */
  status: RequestStatus;
}

/**
 * Check if a given object implements the Request interface.
 */
export function instanceOfRequest(value: object): value is Request {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("date" in value) || value.date === undefined) {
    return false;
  }
  if (!("amount" in value) || value.amount === undefined) {
    return false;
  }
  if (!("status" in value) || value.status === undefined) {
    return false;
  }
  return true;
}

export function RequestFromJSON(json: any): Request {
  return RequestFromJSONTyped(json, false);
}

export function RequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): Request {
  if (json == null) {
    return json;
  }
  return {
    amount: UInt64FromJSON(json.amount),
    date: UnixTimestampFromJSON(json.date),
    id: json.id,
    status: RequestStatusFromJSON(json.status),
  };
}

export function RequestToJSON(json: any): Request {
  return RequestToJSONTyped(json, false);
}

export function RequestToJSONTyped(
  value?: Request | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amount: UInt64ToJSON(value.amount),
    date: UnixTimestampToJSON(value.date),
    id: value.id,
    status: RequestStatusToJSON(value.status),
  };
}
