/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Base64 } from "./Base64";

import { Base64FromJSON, Base64ToJSON } from "./Base64";

/**
 *
 * @export
 * @interface SaveAgentsTeamResp
 */
export interface SaveAgentsTeamResp {
  /**
   *
   * @type {Base64}
   * @memberof SaveAgentsTeamResp
   */
  contract: Base64;
  /**
   *
   * @type {string}
   * @memberof SaveAgentsTeamResp
   */
  version: string;
}

/**
 * Check if a given object implements the SaveAgentsTeamResp interface.
 */
export function instanceOfSaveAgentsTeamResp(value: object): value is SaveAgentsTeamResp {
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  return true;
}

export function SaveAgentsTeamRespFromJSON(json: any): SaveAgentsTeamResp {
  return SaveAgentsTeamRespFromJSONTyped(json, false);
}

export function SaveAgentsTeamRespFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): SaveAgentsTeamResp {
  if (json == null) {
    return json;
  }
  return {
    contract: Base64FromJSON(json.contract),
    version: json.version,
  };
}

export function SaveAgentsTeamRespToJSON(json: any): SaveAgentsTeamResp {
  return SaveAgentsTeamRespToJSONTyped(json, false);
}

export function SaveAgentsTeamRespToJSONTyped(
  value?: SaveAgentsTeamResp | null,
  _ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: Base64ToJSON(value.contract),
    version: value.version,
  };
}
