/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Base64 } from "./Base64";

import { Base64FromJSON, Base64ToJSON } from "./Base64";

/**
 *
 * @export
 * @interface SaveAgentResp
 */
export interface SaveAgentResp {
  /**
   *
   * @type {Base64}
   * @memberof SaveAgentResp
   */
  contract: Base64;
  /**
   *
   * @type {string}
   * @memberof SaveAgentResp
   */
  version: string;
}

/**
 * Check if a given object implements the SaveAgentResp interface.
 */
export function instanceOfSaveAgentResp(value: object): value is SaveAgentResp {
  if (!("version" in value) || value.version === undefined) {
    return false;
  }
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  return true;
}

export function SaveAgentRespFromJSON(json: any): SaveAgentResp {
  return SaveAgentRespFromJSONTyped(json, false);
}

export function SaveAgentRespFromJSONTyped(
  json: any,
  _ignoreDiscriminator: boolean,
): SaveAgentResp {
  if (json == null) {
    return json;
  }
  return {
    contract: Base64FromJSON(json.contract),
    version: json.version,
  };
}

export function SaveAgentRespToJSON(json: any): SaveAgentResp {
  return SaveAgentRespToJSONTyped(json, false);
}

export function SaveAgentRespToJSONTyped(
  value?: SaveAgentResp | null,
  _ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: Base64ToJSON(value.contract),
    version: value.version,
  };
}
