/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PublishToFireskyReq } from "./PublishToFireskyReq";
import type { PublishToFireskyResp } from "./PublishToFireskyResp";
import type { SignedContract } from "./SignedContract";

import {
  PublishToFireskyReqFromJSON,
  PublishToFireskyReqToJSON,
} from "./PublishToFireskyReq";
import {
  PublishToFireskyRespFromJSON,
  PublishToFireskyRespToJSON,
} from "./PublishToFireskyResp";
import { SignedContractFromJSON, SignedContractToJSON } from "./SignedContract";

/**
 *
 * @export
 * @interface SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp
 */
export interface SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp {
  /**
   *
   * @type {PublishToFireskyReq}
   * @memberof SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp
   */
  prepareRequest: PublishToFireskyReq;
  /**
   *
   * @type {PublishToFireskyResp}
   * @memberof SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp
   */
  prepareResponse: PublishToFireskyResp;
  /**
   *
   * @type {SignedContract}
   * @memberof SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp
   */
  request: SignedContract;
  /**
   *
   * @type {string}
   * @memberof SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp
   */
  token: string;
}

/**
 * Check if a given object implements the SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp interface.
 */
export function instanceOfSendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp(
  value: object,
): value is SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp {
  if (!("prepareRequest" in value) || value.prepareRequest === undefined) {
    return false;
  }
  if (!("prepareResponse" in value) || value.prepareResponse === undefined) {
    return false;
  }
  if (!("request" in value) || value.request === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyRespFromJSON(
  json: any,
): SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp {
  return SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyRespFromJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp {
  if (json == null) {
    return json;
  }
  return {
    prepareRequest: PublishToFireskyReqFromJSON(json.prepare_request),
    prepareResponse: PublishToFireskyRespFromJSON(json.prepare_response),
    request: SignedContractFromJSON(json.request),
    token: json.token,
  };
}

export function SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyRespToJSON(
  json: any,
): SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp {
  return SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyRespToJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyRespToJSONTyped(
  value?: SendRequestBodySignedContractPublishToFireskyReqPublishToFireskyResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prepare_request: PublishToFireskyReqToJSON(value.prepareRequest),
    prepare_response: PublishToFireskyRespToJSON(value.prepareResponse),
    request: SignedContractToJSON(value.request),
    token: value.token,
  };
}
