/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateReq } from "./CreateReq";
import type { SaveResp } from "./SaveResp";
import type { SignedContract } from "./SignedContract";

import { CreateReqFromJSON, CreateReqToJSON } from "./CreateReq";
import { SaveRespFromJSON, SaveRespToJSON } from "./SaveResp";
import { SignedContractFromJSON, SignedContractToJSON } from "./SignedContract";

/**
 *
 * @export
 * @interface SendRequestBodySignedContractCreateReqSaveResp
 */
export interface SendRequestBodySignedContractCreateReqSaveResp {
  /**
   *
   * @type {CreateReq}
   * @memberof SendRequestBodySignedContractCreateReqSaveResp
   */
  prepareRequest: CreateReq;
  /**
   *
   * @type {SaveResp}
   * @memberof SendRequestBodySignedContractCreateReqSaveResp
   */
  prepareResponse: SaveResp;
  /**
   *
   * @type {SignedContract}
   * @memberof SendRequestBodySignedContractCreateReqSaveResp
   */
  request: SignedContract;
  /**
   *
   * @type {string}
   * @memberof SendRequestBodySignedContractCreateReqSaveResp
   */
  token: string;
}

/**
 * Check if a given object implements the SendRequestBodySignedContractCreateReqSaveResp interface.
 */
export function instanceOfSendRequestBodySignedContractCreateReqSaveResp(
  value: object,
): value is SendRequestBodySignedContractCreateReqSaveResp {
  if (!("prepareRequest" in value) || value.prepareRequest === undefined) {
    return false;
  }
  if (!("prepareResponse" in value) || value.prepareResponse === undefined) {
    return false;
  }
  if (!("request" in value) || value.request === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function SendRequestBodySignedContractCreateReqSaveRespFromJSON(
  json: any,
): SendRequestBodySignedContractCreateReqSaveResp {
  return SendRequestBodySignedContractCreateReqSaveRespFromJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractCreateReqSaveRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendRequestBodySignedContractCreateReqSaveResp {
  if (json == null) {
    return json;
  }
  return {
    prepareRequest: CreateReqFromJSON(json.prepare_request),
    prepareResponse: SaveRespFromJSON(json.prepare_response),
    request: SignedContractFromJSON(json.request),
    token: json.token,
  };
}

export function SendRequestBodySignedContractCreateReqSaveRespToJSON(
  json: any,
): SendRequestBodySignedContractCreateReqSaveResp {
  return SendRequestBodySignedContractCreateReqSaveRespToJSONTyped(json, false);
}

export function SendRequestBodySignedContractCreateReqSaveRespToJSONTyped(
  value?: SendRequestBodySignedContractCreateReqSaveResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prepare_request: CreateReqToJSON(value.prepareRequest),
    prepare_response: SaveRespToJSON(value.prepareResponse),
    request: SignedContractToJSON(value.request),
    token: value.token,
  };
}
