/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateOslfReq } from "./CreateOslfReq";
import type { SaveOslfResp } from "./SaveOslfResp";
import type { SignedContract } from "./SignedContract";

import { CreateOslfReqFromJSON, CreateOslfReqToJSON } from "./CreateOslfReq";
import { SaveOslfRespFromJSON, SaveOslfRespToJSON } from "./SaveOslfResp";
import { SignedContractFromJSON, SignedContractToJSON } from "./SignedContract";

/**
 *
 * @export
 * @interface SendRequestBodySignedContractCreateOslfReqSaveOslfResp
 */
export interface SendRequestBodySignedContractCreateOslfReqSaveOslfResp {
  /**
   *
   * @type {CreateOslfReq}
   * @memberof SendRequestBodySignedContractCreateOslfReqSaveOslfResp
   */
  prepareRequest: CreateOslfReq;
  /**
   *
   * @type {SaveOslfResp}
   * @memberof SendRequestBodySignedContractCreateOslfReqSaveOslfResp
   */
  prepareResponse: SaveOslfResp;
  /**
   *
   * @type {SignedContract}
   * @memberof SendRequestBodySignedContractCreateOslfReqSaveOslfResp
   */
  request: SignedContract;
  /**
   *
   * @type {string}
   * @memberof SendRequestBodySignedContractCreateOslfReqSaveOslfResp
   */
  token: string;
}

/**
 * Check if a given object implements the SendRequestBodySignedContractCreateOslfReqSaveOslfResp interface.
 */
export function instanceOfSendRequestBodySignedContractCreateOslfReqSaveOslfResp(
  value: object,
): value is SendRequestBodySignedContractCreateOslfReqSaveOslfResp {
  if (!("prepareRequest" in value) || value.prepareRequest === undefined) {
    return false;
  }
  if (!("prepareResponse" in value) || value.prepareResponse === undefined) {
    return false;
  }
  if (!("request" in value) || value.request === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function SendRequestBodySignedContractCreateOslfReqSaveOslfRespFromJSON(
  json: any,
): SendRequestBodySignedContractCreateOslfReqSaveOslfResp {
  return SendRequestBodySignedContractCreateOslfReqSaveOslfRespFromJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractCreateOslfReqSaveOslfRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendRequestBodySignedContractCreateOslfReqSaveOslfResp {
  if (json == null) {
    return json;
  }
  return {
    prepareRequest: CreateOslfReqFromJSON(json.prepare_request),
    prepareResponse: SaveOslfRespFromJSON(json.prepare_response),
    request: SignedContractFromJSON(json.request),
    token: json.token,
  };
}

export function SendRequestBodySignedContractCreateOslfReqSaveOslfRespToJSON(
  json: any,
): SendRequestBodySignedContractCreateOslfReqSaveOslfResp {
  return SendRequestBodySignedContractCreateOslfReqSaveOslfRespToJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractCreateOslfReqSaveOslfRespToJSONTyped(
  value?: SendRequestBodySignedContractCreateOslfReqSaveOslfResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prepare_request: CreateOslfReqToJSON(value.prepareRequest),
    prepare_response: SaveOslfRespToJSON(value.prepareResponse),
    request: SignedContractToJSON(value.request),
    token: value.token,
  };
}
