/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateAgentsTeamReq } from "./CreateAgentsTeamReq";
import type { SaveAgentsTeamResp } from "./SaveAgentsTeamResp";
import type { SignedContract } from "./SignedContract";

import {
  CreateAgentsTeamReqFromJSON,
  CreateAgentsTeamReqToJSON,
} from "./CreateAgentsTeamReq";
import {
  SaveAgentsTeamRespFromJSON,
  SaveAgentsTeamRespToJSON,
} from "./SaveAgentsTeamResp";
import { SignedContractFromJSON, SignedContractToJSON } from "./SignedContract";

/**
 *
 * @export
 * @interface SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp
 */
export interface SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp {
  /**
   *
   * @type {CreateAgentsTeamReq}
   * @memberof SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp
   */
  prepareRequest: CreateAgentsTeamReq;
  /**
   *
   * @type {SaveAgentsTeamResp}
   * @memberof SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp
   */
  prepareResponse: SaveAgentsTeamResp;
  /**
   *
   * @type {SignedContract}
   * @memberof SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp
   */
  request: SignedContract;
  /**
   *
   * @type {string}
   * @memberof SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp
   */
  token: string;
}

/**
 * Check if a given object implements the SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp interface.
 */
export function instanceOfSendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp(
  value: object,
): value is SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp {
  if (!("prepareRequest" in value) || value.prepareRequest === undefined) {
    return false;
  }
  if (!("prepareResponse" in value) || value.prepareResponse === undefined) {
    return false;
  }
  if (!("request" in value) || value.request === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamRespFromJSON(
  json: any,
): SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp {
  return SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamRespFromJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp {
  if (json == null) {
    return json;
  }
  return {
    prepareRequest: CreateAgentsTeamReqFromJSON(json.prepare_request),
    prepareResponse: SaveAgentsTeamRespFromJSON(json.prepare_response),
    request: SignedContractFromJSON(json.request),
    token: json.token,
  };
}

export function SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamRespToJSON(
  json: any,
): SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp {
  return SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamRespToJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamRespToJSONTyped(
  value?: SendRequestBodySignedContractCreateAgentsTeamReqSaveAgentsTeamResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prepare_request: CreateAgentsTeamReqToJSON(value.prepareRequest),
    prepare_response: SaveAgentsTeamRespToJSON(value.prepareResponse),
    request: SignedContractToJSON(value.request),
    token: value.token,
  };
}
