/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { DeploySignedRunAgentsTeamFireskyReq } from "./DeploySignedRunAgentsTeamFireskyReq";
import type { RunAgentsTeamReq } from "./RunAgentsTeamReq";
import type { RunAgentsTeamResp } from "./RunAgentsTeamResp";

import {
  DeploySignedRunAgentsTeamFireskyReqFromJSON,
  DeploySignedRunAgentsTeamFireskyReqToJSON,
} from "./DeploySignedRunAgentsTeamFireskyReq";
import {
  RunAgentsTeamReqFromJSON,
  RunAgentsTeamReqToJSON,
} from "./RunAgentsTeamReq";
import {
  RunAgentsTeamRespFromJSON,
  RunAgentsTeamRespToJSON,
} from "./RunAgentsTeamResp";

/**
 *
 * @export
 * @interface SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp
 */
export interface SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp {
  /**
   *
   * @type {RunAgentsTeamReq}
   * @memberof SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp
   */
  prepareRequest: RunAgentsTeamReq;
  /**
   *
   * @type {RunAgentsTeamResp}
   * @memberof SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp
   */
  prepareResponse: RunAgentsTeamResp;
  /**
   *
   * @type {DeploySignedRunAgentsTeamFireskyReq}
   * @memberof SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp
   */
  request: DeploySignedRunAgentsTeamFireskyReq;
  /**
   *
   * @type {string}
   * @memberof SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp
   */
  token: string;
}

/**
 * Check if a given object implements the SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp interface.
 */
export function instanceOfSendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp(
  value: object,
): value is SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp {
  if (!("prepareRequest" in value) || value.prepareRequest === undefined) {
    return false;
  }
  if (!("prepareResponse" in value) || value.prepareResponse === undefined) {
    return false;
  }
  if (!("request" in value) || value.request === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamRespFromJSON(
  json: any,
): SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp {
  return SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamRespFromJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp {
  if (json == null) {
    return json;
  }
  return {
    prepareRequest: RunAgentsTeamReqFromJSON(json.prepare_request),
    prepareResponse: RunAgentsTeamRespFromJSON(json.prepare_response),
    request: DeploySignedRunAgentsTeamFireskyReqFromJSON(json.request),
    token: json.token,
  };
}

export function SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamRespToJSON(
  json: any,
): SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp {
  return SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamRespToJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamRespToJSONTyped(
  value?: SendRequestBodyDeploySignedRunAgentsTeamFireskyReqRunAgentsTeamReqRunAgentsTeamResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prepare_request: RunAgentsTeamReqToJSON(value.prepareRequest),
    prepare_response: RunAgentsTeamRespToJSON(value.prepareResponse),
    request: DeploySignedRunAgentsTeamFireskyReqToJSON(value.request),
    token: value.token,
  };
}
