/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateOslfReq } from "./CreateOslfReq";
import type { CreateOslfResp } from "./CreateOslfResp";
import type { SignedContract } from "./SignedContract";

import { CreateOslfReqFromJSON, CreateOslfReqToJSON } from "./CreateOslfReq";
import { CreateOslfRespFromJSON, CreateOslfRespToJSON } from "./CreateOslfResp";
import { SignedContractFromJSON, SignedContractToJSON } from "./SignedContract";

/**
 *
 * @export
 * @interface SendRequestBodySignedContractCreateOslfReqCreateOslfResp
 */
export interface SendRequestBodySignedContractCreateOslfReqCreateOslfResp {
  /**
   *
   * @type {CreateOslfReq}
   * @memberof SendRequestBodySignedContractCreateOslfReqCreateOslfResp
   */
  prepareRequest: CreateOslfReq;
  /**
   *
   * @type {CreateOslfResp}
   * @memberof SendRequestBodySignedContractCreateOslfReqCreateOslfResp
   */
  prepareResponse: CreateOslfResp;
  /**
   *
   * @type {SignedContract}
   * @memberof SendRequestBodySignedContractCreateOslfReqCreateOslfResp
   */
  request: SignedContract;
  /**
   *
   * @type {string}
   * @memberof SendRequestBodySignedContractCreateOslfReqCreateOslfResp
   */
  token: string;
}

/**
 * Check if a given object implements the SendRequestBodySignedContractCreateOslfReqCreateOslfResp interface.
 */
export function instanceOfSendRequestBodySignedContractCreateOslfReqCreateOslfResp(
  value: object,
): value is SendRequestBodySignedContractCreateOslfReqCreateOslfResp {
  if (!("prepareRequest" in value) || value.prepareRequest === undefined) {
    return false;
  }
  if (!("prepareResponse" in value) || value.prepareResponse === undefined) {
    return false;
  }
  if (!("request" in value) || value.request === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function SendRequestBodySignedContractCreateOslfReqCreateOslfRespFromJSON(
  json: any,
): SendRequestBodySignedContractCreateOslfReqCreateOslfResp {
  return SendRequestBodySignedContractCreateOslfReqCreateOslfRespFromJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractCreateOslfReqCreateOslfRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendRequestBodySignedContractCreateOslfReqCreateOslfResp {
  if (json == null) {
    return json;
  }
  return {
    prepareRequest: CreateOslfReqFromJSON(json.prepare_request),
    prepareResponse: CreateOslfRespFromJSON(json.prepare_response),
    request: SignedContractFromJSON(json.request),
    token: json.token,
  };
}

export function SendRequestBodySignedContractCreateOslfReqCreateOslfRespToJSON(
  json: any,
): SendRequestBodySignedContractCreateOslfReqCreateOslfResp {
  return SendRequestBodySignedContractCreateOslfReqCreateOslfRespToJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractCreateOslfReqCreateOslfRespToJSONTyped(
  value?: SendRequestBodySignedContractCreateOslfReqCreateOslfResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prepare_request: CreateOslfReqToJSON(value.prepareRequest),
    prepare_response: CreateOslfRespToJSON(value.prepareResponse),
    request: SignedContractToJSON(value.request),
    token: value.token,
  };
}
