/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateReq } from "./CreateReq";
import type { CreateResp } from "./CreateResp";
import type { SignedContract } from "./SignedContract";

import { CreateReqFromJSON, CreateReqToJSON } from "./CreateReq";
import { CreateRespFromJSON, CreateRespToJSON } from "./CreateResp";
import { SignedContractFromJSON, SignedContractToJSON } from "./SignedContract";

/**
 *
 * @export
 * @interface SendRequestBodySignedContractCreateReqCreateResp
 */
export interface SendRequestBodySignedContractCreateReqCreateResp {
  /**
   *
   * @type {CreateReq}
   * @memberof SendRequestBodySignedContractCreateReqCreateResp
   */
  prepareRequest: CreateReq;
  /**
   *
   * @type {CreateResp}
   * @memberof SendRequestBodySignedContractCreateReqCreateResp
   */
  prepareResponse: CreateResp;
  /**
   *
   * @type {SignedContract}
   * @memberof SendRequestBodySignedContractCreateReqCreateResp
   */
  request: SignedContract;
  /**
   *
   * @type {string}
   * @memberof SendRequestBodySignedContractCreateReqCreateResp
   */
  token: string;
}

/**
 * Check if a given object implements the SendRequestBodySignedContractCreateReqCreateResp interface.
 */
export function instanceOfSendRequestBodySignedContractCreateReqCreateResp(
  value: object,
): value is SendRequestBodySignedContractCreateReqCreateResp {
  if (!("prepareRequest" in value) || value.prepareRequest === undefined) {
    return false;
  }
  if (!("prepareResponse" in value) || value.prepareResponse === undefined) {
    return false;
  }
  if (!("request" in value) || value.request === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function SendRequestBodySignedContractCreateReqCreateRespFromJSON(
  json: any,
): SendRequestBodySignedContractCreateReqCreateResp {
  return SendRequestBodySignedContractCreateReqCreateRespFromJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractCreateReqCreateRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendRequestBodySignedContractCreateReqCreateResp {
  if (json == null) {
    return json;
  }
  return {
    prepareRequest: CreateReqFromJSON(json.prepare_request),
    prepareResponse: CreateRespFromJSON(json.prepare_response),
    request: SignedContractFromJSON(json.request),
    token: json.token,
  };
}

export function SendRequestBodySignedContractCreateReqCreateRespToJSON(
  json: any,
): SendRequestBodySignedContractCreateReqCreateResp {
  return SendRequestBodySignedContractCreateReqCreateRespToJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractCreateReqCreateRespToJSONTyped(
  value?: SendRequestBodySignedContractCreateReqCreateResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prepare_request: CreateReqToJSON(value.prepareRequest),
    prepare_response: CreateRespToJSON(value.prepareResponse),
    request: SignedContractToJSON(value.request),
    token: value.token,
  };
}
