/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { CreateAgentsTeamReq } from "./CreateAgentsTeamReq";
import type { CreateAgentsTeamResp } from "./CreateAgentsTeamResp";
import type { SignedContract } from "./SignedContract";

import {
  CreateAgentsTeamReqFromJSON,
  CreateAgentsTeamReqToJSON,
} from "./CreateAgentsTeamReq";
import {
  CreateAgentsTeamRespFromJSON,
  CreateAgentsTeamRespToJSON,
} from "./CreateAgentsTeamResp";
import { SignedContractFromJSON, SignedContractToJSON } from "./SignedContract";

/**
 *
 * @export
 * @interface SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp
 */
export interface SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp {
  /**
   *
   * @type {CreateAgentsTeamReq}
   * @memberof SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp
   */
  prepareRequest: CreateAgentsTeamReq;
  /**
   *
   * @type {CreateAgentsTeamResp}
   * @memberof SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp
   */
  prepareResponse: CreateAgentsTeamResp;
  /**
   *
   * @type {SignedContract}
   * @memberof SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp
   */
  request: SignedContract;
  /**
   *
   * @type {string}
   * @memberof SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp
   */
  token: string;
}

/**
 * Check if a given object implements the SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp interface.
 */
export function instanceOfSendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp(
  value: object,
): value is SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp {
  if (!("prepareRequest" in value) || value.prepareRequest === undefined) {
    return false;
  }
  if (!("prepareResponse" in value) || value.prepareResponse === undefined) {
    return false;
  }
  if (!("request" in value) || value.request === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamRespFromJSON(
  json: any,
): SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp {
  return SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamRespFromJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp {
  if (json == null) {
    return json;
  }
  return {
    prepareRequest: CreateAgentsTeamReqFromJSON(json.prepare_request),
    prepareResponse: CreateAgentsTeamRespFromJSON(json.prepare_response),
    request: SignedContractFromJSON(json.request),
    token: json.token,
  };
}

export function SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamRespToJSON(
  json: any,
): SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp {
  return SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamRespToJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamRespToJSONTyped(
  value?: SendRequestBodySignedContractCreateAgentsTeamReqCreateAgentsTeamResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prepare_request: CreateAgentsTeamReqToJSON(value.prepareRequest),
    prepare_response: CreateAgentsTeamRespToJSON(value.prepareResponse),
    request: SignedContractToJSON(value.request),
    token: value.token,
  };
}
