/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { RunAgentsTeamReq } from "./RunAgentsTeamReq";
import type { RunAgentsTeamResp } from "./RunAgentsTeamResp";
import type { SignedContract } from "./SignedContract";

import {
  RunAgentsTeamReqFromJSON,
  RunAgentsTeamReqToJSON,
} from "./RunAgentsTeamReq";
import {
  RunAgentsTeamRespFromJSON,
  RunAgentsTeamRespToJSON,
} from "./RunAgentsTeamResp";
import { SignedContractFromJSON, SignedContractToJSON } from "./SignedContract";

/**
 *
 * @export
 * @interface SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp
 */
export interface SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp {
  /**
   *
   * @type {RunAgentsTeamReq}
   * @memberof SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp
   */
  prepareRequest: RunAgentsTeamReq;
  /**
   *
   * @type {RunAgentsTeamResp}
   * @memberof SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp
   */
  prepareResponse: RunAgentsTeamResp;
  /**
   *
   * @type {SignedContract}
   * @memberof SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp
   */
  request: SignedContract;
  /**
   *
   * @type {string}
   * @memberof SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp
   */
  token: string;
}

/**
 * Check if a given object implements the SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp interface.
 */
export function instanceOfSendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp(
  value: object,
): value is SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp {
  if (!("prepareRequest" in value) || value.prepareRequest === undefined) {
    return false;
  }
  if (!("prepareResponse" in value) || value.prepareResponse === undefined) {
    return false;
  }
  if (!("request" in value) || value.request === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamRespFromJSON(
  json: any,
): SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp {
  return SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamRespFromJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp {
  if (json == null) {
    return json;
  }
  return {
    prepareRequest: RunAgentsTeamReqFromJSON(json.prepare_request),
    prepareResponse: RunAgentsTeamRespFromJSON(json.prepare_response),
    request: SignedContractFromJSON(json.request),
    token: json.token,
  };
}

export function SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamRespToJSON(
  json: any,
): SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp {
  return SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamRespToJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamRespToJSONTyped(
  value?: SendRequestBodySignedContractRunAgentsTeamReqRunAgentsTeamResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prepare_request: RunAgentsTeamReqToJSON(value.prepareRequest),
    prepare_response: RunAgentsTeamRespToJSON(value.prepareResponse),
    request: SignedContractToJSON(value.request),
    token: value.token,
  };
}
