/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { SignedContract } from "./SignedContract";
import type { TransferReq } from "./TransferReq";
import type { TransferResp } from "./TransferResp";

import { SignedContractFromJSON, SignedContractToJSON } from "./SignedContract";
import { TransferReqFromJSON, TransferReqToJSON } from "./TransferReq";
import { TransferRespFromJSON, TransferRespToJSON } from "./TransferResp";

/**
 *
 * @export
 * @interface SendRequestBodySignedContractTransferReqTransferResp
 */
export interface SendRequestBodySignedContractTransferReqTransferResp {
  /**
   *
   * @type {TransferReq}
   * @memberof SendRequestBodySignedContractTransferReqTransferResp
   */
  prepareRequest: TransferReq;
  /**
   *
   * @type {TransferResp}
   * @memberof SendRequestBodySignedContractTransferReqTransferResp
   */
  prepareResponse: TransferResp;
  /**
   *
   * @type {SignedContract}
   * @memberof SendRequestBodySignedContractTransferReqTransferResp
   */
  request: SignedContract;
  /**
   *
   * @type {string}
   * @memberof SendRequestBodySignedContractTransferReqTransferResp
   */
  token: string;
}

/**
 * Check if a given object implements the SendRequestBodySignedContractTransferReqTransferResp interface.
 */
export function instanceOfSendRequestBodySignedContractTransferReqTransferResp(
  value: object,
): value is SendRequestBodySignedContractTransferReqTransferResp {
  if (!("prepareRequest" in value) || value.prepareRequest === undefined) {
    return false;
  }
  if (!("prepareResponse" in value) || value.prepareResponse === undefined) {
    return false;
  }
  if (!("request" in value) || value.request === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function SendRequestBodySignedContractTransferReqTransferRespFromJSON(
  json: any,
): SendRequestBodySignedContractTransferReqTransferResp {
  return SendRequestBodySignedContractTransferReqTransferRespFromJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractTransferReqTransferRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendRequestBodySignedContractTransferReqTransferResp {
  if (json == null) {
    return json;
  }
  return {
    prepareRequest: TransferReqFromJSON(json.prepare_request),
    prepareResponse: TransferRespFromJSON(json.prepare_response),
    request: SignedContractFromJSON(json.request),
    token: json.token,
  };
}

export function SendRequestBodySignedContractTransferReqTransferRespToJSON(
  json: any,
): SendRequestBodySignedContractTransferReqTransferResp {
  return SendRequestBodySignedContractTransferReqTransferRespToJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractTransferReqTransferRespToJSONTyped(
  value?: SendRequestBodySignedContractTransferReqTransferResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prepare_request: TransferReqToJSON(value.prepareRequest),
    prepare_response: TransferRespToJSON(value.prepareResponse),
    request: SignedContractToJSON(value.request),
    token: value.token,
  };
}
