/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PublishAgentsTeamToFireskyReq } from "./PublishAgentsTeamToFireskyReq";
import type { PublishAgentsTeamToFireskyResp } from "./PublishAgentsTeamToFireskyResp";
import type { SignedContract } from "./SignedContract";

import {
  PublishAgentsTeamToFireskyReqFromJSON,
  PublishAgentsTeamToFireskyReqToJSON,
} from "./PublishAgentsTeamToFireskyReq";
import {
  PublishAgentsTeamToFireskyRespFromJSON,
  PublishAgentsTeamToFireskyRespToJSON,
} from "./PublishAgentsTeamToFireskyResp";
import { SignedContractFromJSON, SignedContractToJSON } from "./SignedContract";

/**
 *
 * @export
 * @interface SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp
 */
export interface SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp {
  /**
   *
   * @type {PublishAgentsTeamToFireskyReq}
   * @memberof SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp
   */
  prepareRequest: PublishAgentsTeamToFireskyReq;
  /**
   *
   * @type {PublishAgentsTeamToFireskyResp}
   * @memberof SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp
   */
  prepareResponse: PublishAgentsTeamToFireskyResp;
  /**
   *
   * @type {SignedContract}
   * @memberof SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp
   */
  request: SignedContract;
  /**
   *
   * @type {string}
   * @memberof SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp
   */
  token: string;
}

/**
 * Check if a given object implements the SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp interface.
 */
export function instanceOfSendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp(
  value: object,
): value is SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp {
  if (!("prepareRequest" in value) || value.prepareRequest === undefined) {
    return false;
  }
  if (!("prepareResponse" in value) || value.prepareResponse === undefined) {
    return false;
  }
  if (!("request" in value) || value.request === undefined) {
    return false;
  }
  if (!("token" in value) || value.token === undefined) {
    return false;
  }
  return true;
}

export function SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyRespFromJSON(
  json: any,
): SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp {
  return SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyRespFromJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyRespFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp {
  if (json == null) {
    return json;
  }
  return {
    prepareRequest: PublishAgentsTeamToFireskyReqFromJSON(json.prepare_request),
    prepareResponse: PublishAgentsTeamToFireskyRespFromJSON(
      json.prepare_response,
    ),
    request: SignedContractFromJSON(json.request),
    token: json.token,
  };
}

export function SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyRespToJSON(
  json: any,
): SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp {
  return SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyRespToJSONTyped(
    json,
    false,
  );
}

export function SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyRespToJSONTyped(
  value?: SendRequestBodySignedContractPublishAgentsTeamToFireskyReqPublishAgentsTeamToFireskyResp | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    prepare_request: PublishAgentsTeamToFireskyReqToJSON(value.prepareRequest),
    prepare_response: PublishAgentsTeamToFireskyRespToJSON(
      value.prepareResponse,
    ),
    request: SignedContractToJSON(value.request),
    token: value.token,
  };
}
