/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Base64 } from "./Base64";

import { Base64FromJSON, Base64ToJSON } from "./Base64";

/**
 *
 * @export
 * @interface SignedContract
 */
export interface SignedContract {
  /**
   *
   * @type {Base64}
   * @memberof SignedContract
   */
  contract: Base64;
  /**
   *
   * @type {Base64}
   * @memberof SignedContract
   */
  deployer: Base64;
  /**
   *
   * @type {Base64}
   * @memberof SignedContract
   */
  sig: Base64;
  /**
   *
   * @type {string}
   * @memberof SignedContract
   */
  sigAlgorithm: string;
}

/**
 * Check if a given object implements the SignedContract interface.
 */
export function instanceOfSignedContract(
  value: object,
): value is SignedContract {
  if (!("contract" in value) || value.contract === undefined) {
    return false;
  }
  if (!("sig" in value) || value.sig === undefined) {
    return false;
  }
  if (!("sigAlgorithm" in value) || value.sigAlgorithm === undefined) {
    return false;
  }
  if (!("deployer" in value) || value.deployer === undefined) {
    return false;
  }
  return true;
}

export function SignedContractFromJSON(json: any): SignedContract {
  return SignedContractFromJSONTyped(json, false);
}

export function SignedContractFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): SignedContract {
  if (json == null) {
    return json;
  }
  return {
    contract: Base64FromJSON(json.contract),
    deployer: Base64FromJSON(json.deployer),
    sig: Base64FromJSON(json.sig),
    sigAlgorithm: json.sig_algorithm,
  };
}

export function SignedContractToJSON(json: any): SignedContract {
  return SignedContractToJSONTyped(json, false);
}

export function SignedContractToJSONTyped(
  value?: SignedContract | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    contract: Base64ToJSON(value.contract),
    deployer: Base64ToJSON(value.deployer),
    sig: Base64ToJSON(value.sig),
    sig_algorithm: value.sigAlgorithm,
  };
}
