/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Direction } from "./Direction";
import { DirectionFromJSON, DirectionToJSON } from "./Direction";
import type { UInt64 } from "./UInt64";
import { UInt64FromJSON, UInt64ToJSON } from "./UInt64";
import type { UnixTimestamp } from "./UnixTimestamp";
import { UnixTimestampFromJSON, UnixTimestampToJSON } from "./UnixTimestamp";

/**
 *
 * @export
 * @interface Transfer
 */
export interface Transfer {
  /**
   *
   * @type {UInt64}
   * @memberof Transfer
   */
  amount: UInt64;
  /**
   *
   * @type {UInt64}
   * @memberof Transfer
   */
  cost: UInt64;
  /**
   *
   * @type {UnixTimestamp}
   * @memberof Transfer
   */
  date: UnixTimestamp;
  /**
   *
   * @type {Direction}
   * @memberof Transfer
   */
  direction: Direction;
  /**
   *
   * @type {string}
   * @memberof Transfer
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof Transfer
   */
  toAddress: string;
}

/**
 * Check if a given object implements the Transfer interface.
 */
export function instanceOfTransfer(value: object): value is Transfer {
  if (!("id" in value) || value.id === undefined) {
    return false;
  }
  if (!("direction" in value) || value.direction === undefined) {
    return false;
  }
  if (!("date" in value) || value.date === undefined) {
    return false;
  }
  if (!("amount" in value) || value.amount === undefined) {
    return false;
  }
  if (!("toAddress" in value) || value.toAddress === undefined) {
    return false;
  }
  if (!("cost" in value) || value.cost === undefined) {
    return false;
  }
  return true;
}

export function TransferFromJSON(json: any): Transfer {
  return TransferFromJSONTyped(json, false);
}

export function TransferFromJSONTyped(json: any, ignoreDiscriminator: boolean): Transfer {
  if (json == null) {
    return json;
  }
  return {
    amount: UInt64FromJSON(json.amount),
    cost: UInt64FromJSON(json.cost),
    date: UnixTimestampFromJSON(json.date),
    direction: DirectionFromJSON(json.direction),
    id: json.id,
    toAddress: json.to_address,
  };
}

export function TransferToJSON(json: any): Transfer {
  return TransferToJSONTyped(json, false);
}

export function TransferToJSONTyped(
  value?: Transfer | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    amount: UInt64ToJSON(value.amount),
    cost: UInt64ToJSON(value.cost),
    date: UnixTimestampToJSON(value.date),
    direction: DirectionToJSON(value.direction),
    id: value.id,
    to_address: value.toAddress,
  };
}
