/**
 * Embers API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { Name } from "./Name";

import { NameFromJSON, NameToJSON } from "./Name";

/**
 *
 * @export
 * @interface Vertex
 */
export interface Vertex {
  /**
   *
   * @type {Name}
   * @memberof Vertex
   */
  name: Name;
}

/**
 * Check if a given object implements the Vertex interface.
 */
export function instanceOfVertex(value: object): value is Vertex {
  if (!("name" in value) || value.name === undefined) {
    return false;
  }
  return true;
}

export function VertexFromJSON(json: any): Vertex {
  return VertexFromJSONTyped(json, false);
}

export function VertexFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Vertex {
  if (json == null) {
    return json;
  }
  return {
    name: NameFromJSON(json.name),
  };
}

export function VertexToJSON(json: any): Vertex {
  return VertexToJSONTyped(json, false);
}

export function VertexToJSONTyped(
  value?: Vertex | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    name: NameToJSON(value.name),
  };
}
