declare const classNames: {
  readonly "deploy-container": "deploy-container";
  readonly "stepper-container": "stepper-container";
  readonly "content-container": "content-container";
  readonly "title-container": "title-container";
  readonly "description-container": "description-container";
  readonly "details-container": "details-container";
  readonly "detail-row": "detail-row";
  readonly "label-container": "label-container";
  readonly divider: "divider";
  readonly "form-section": "form-section";
  readonly "form-label": "form-label";
  readonly "form-input": "form-input";
  readonly "form-textarea": "form-textarea";
  readonly "section-title": "section-title";
  readonly "form-fields": "form-fields";
  readonly "button-container": "button-container";
  readonly "draft-button": "draft-button";
  readonly "deploy-button": "deploy-button";
  readonly "estimation-bar": "estimation-bar";
  readonly "estimation-value": "estimation-value";
};
export default classNames;
